services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: indoorgrid-system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d indoorgrid-system"]
      interval: 5s
      timeout: 5s
      retries: 3

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    user: "1883:1883"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  db-data: