// preset_status.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Mon Nov  4 18:00:55 UTC 2024

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf message received from camera containing preset status

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: preset_status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumFlatMode int32

const (
	EnumFlatMode_FLAT_MODE_UNKNOWN              EnumFlatMode = -1
	EnumFlatMode_FLAT_MODE_PLAYBACK             EnumFlatMode = 4
	EnumFlatMode_FLAT_MODE_SETUP                EnumFlatMode = 5
	EnumFlatMode_FLAT_MODE_VIDEO                EnumFlatMode = 12
	EnumFlatMode_FLAT_MODE_TIME_LAPSE_VIDEO     EnumFlatMode = 13
	EnumFlatMode_FLAT_MODE_LOOPING              EnumFlatMode = 15
	EnumFlatMode_FLAT_MODE_PHOTO_SINGLE         EnumFlatMode = 16
	EnumFlatMode_FLAT_MODE_PHOTO                EnumFlatMode = 17
	EnumFlatMode_FLAT_MODE_PHOTO_NIGHT          EnumFlatMode = 18
	EnumFlatMode_FLAT_MODE_PHOTO_BURST          EnumFlatMode = 19
	EnumFlatMode_FLAT_MODE_TIME_LAPSE_PHOTO     EnumFlatMode = 20
	EnumFlatMode_FLAT_MODE_NIGHT_LAPSE_PHOTO    EnumFlatMode = 21
	EnumFlatMode_FLAT_MODE_BROADCAST_RECORD     EnumFlatMode = 22
	EnumFlatMode_FLAT_MODE_BROADCAST_BROADCAST  EnumFlatMode = 23
	EnumFlatMode_FLAT_MODE_TIME_WARP_VIDEO      EnumFlatMode = 24
	EnumFlatMode_FLAT_MODE_LIVE_BURST           EnumFlatMode = 25
	EnumFlatMode_FLAT_MODE_NIGHT_LAPSE_VIDEO    EnumFlatMode = 26
	EnumFlatMode_FLAT_MODE_SLOMO                EnumFlatMode = 27
	EnumFlatMode_FLAT_MODE_IDLE                 EnumFlatMode = 28
	EnumFlatMode_FLAT_MODE_VIDEO_STAR_TRAIL     EnumFlatMode = 29
	EnumFlatMode_FLAT_MODE_VIDEO_LIGHT_PAINTING EnumFlatMode = 30
	EnumFlatMode_FLAT_MODE_VIDEO_LIGHT_TRAIL    EnumFlatMode = 31
	EnumFlatMode_FLAT_MODE_VIDEO_BURST_SLOMO    EnumFlatMode = 32
)

// Enum value maps for EnumFlatMode.
var (
	EnumFlatMode_name = map[int32]string{
		-1: "FLAT_MODE_UNKNOWN",
		4:  "FLAT_MODE_PLAYBACK",
		5:  "FLAT_MODE_SETUP",
		12: "FLAT_MODE_VIDEO",
		13: "FLAT_MODE_TIME_LAPSE_VIDEO",
		15: "FLAT_MODE_LOOPING",
		16: "FLAT_MODE_PHOTO_SINGLE",
		17: "FLAT_MODE_PHOTO",
		18: "FLAT_MODE_PHOTO_NIGHT",
		19: "FLAT_MODE_PHOTO_BURST",
		20: "FLAT_MODE_TIME_LAPSE_PHOTO",
		21: "FLAT_MODE_NIGHT_LAPSE_PHOTO",
		22: "FLAT_MODE_BROADCAST_RECORD",
		23: "FLAT_MODE_BROADCAST_BROADCAST",
		24: "FLAT_MODE_TIME_WARP_VIDEO",
		25: "FLAT_MODE_LIVE_BURST",
		26: "FLAT_MODE_NIGHT_LAPSE_VIDEO",
		27: "FLAT_MODE_SLOMO",
		28: "FLAT_MODE_IDLE",
		29: "FLAT_MODE_VIDEO_STAR_TRAIL",
		30: "FLAT_MODE_VIDEO_LIGHT_PAINTING",
		31: "FLAT_MODE_VIDEO_LIGHT_TRAIL",
		32: "FLAT_MODE_VIDEO_BURST_SLOMO",
	}
	EnumFlatMode_value = map[string]int32{
		"FLAT_MODE_UNKNOWN":              -1,
		"FLAT_MODE_PLAYBACK":             4,
		"FLAT_MODE_SETUP":                5,
		"FLAT_MODE_VIDEO":                12,
		"FLAT_MODE_TIME_LAPSE_VIDEO":     13,
		"FLAT_MODE_LOOPING":              15,
		"FLAT_MODE_PHOTO_SINGLE":         16,
		"FLAT_MODE_PHOTO":                17,
		"FLAT_MODE_PHOTO_NIGHT":          18,
		"FLAT_MODE_PHOTO_BURST":          19,
		"FLAT_MODE_TIME_LAPSE_PHOTO":     20,
		"FLAT_MODE_NIGHT_LAPSE_PHOTO":    21,
		"FLAT_MODE_BROADCAST_RECORD":     22,
		"FLAT_MODE_BROADCAST_BROADCAST":  23,
		"FLAT_MODE_TIME_WARP_VIDEO":      24,
		"FLAT_MODE_LIVE_BURST":           25,
		"FLAT_MODE_NIGHT_LAPSE_VIDEO":    26,
		"FLAT_MODE_SLOMO":                27,
		"FLAT_MODE_IDLE":                 28,
		"FLAT_MODE_VIDEO_STAR_TRAIL":     29,
		"FLAT_MODE_VIDEO_LIGHT_PAINTING": 30,
		"FLAT_MODE_VIDEO_LIGHT_TRAIL":    31,
		"FLAT_MODE_VIDEO_BURST_SLOMO":    32,
	}
)

func (x EnumFlatMode) Enum() *EnumFlatMode {
	p := new(EnumFlatMode)
	*p = x
	return p
}

func (x EnumFlatMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumFlatMode) Descriptor() protoreflect.EnumDescriptor {
	return file_preset_status_proto_enumTypes[0].Descriptor()
}

func (EnumFlatMode) Type() protoreflect.EnumType {
	return &file_preset_status_proto_enumTypes[0]
}

func (x EnumFlatMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumFlatMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumFlatMode(num)
	return nil
}

// Deprecated: Use EnumFlatMode.Descriptor instead.
func (EnumFlatMode) EnumDescriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{0}
}

type EnumPresetGroup int32

const (
	EnumPresetGroup_PRESET_GROUP_ID_VIDEO     EnumPresetGroup = 1000
	EnumPresetGroup_PRESET_GROUP_ID_PHOTO     EnumPresetGroup = 1001
	EnumPresetGroup_PRESET_GROUP_ID_TIMELAPSE EnumPresetGroup = 1002
	EnumPresetGroup_PRESET_GROUP_ID_GENERAL   EnumPresetGroup = 2000
)

// Enum value maps for EnumPresetGroup.
var (
	EnumPresetGroup_name = map[int32]string{
		1000: "PRESET_GROUP_ID_VIDEO",
		1001: "PRESET_GROUP_ID_PHOTO",
		1002: "PRESET_GROUP_ID_TIMELAPSE",
		2000: "PRESET_GROUP_ID_GENERAL",
	}
	EnumPresetGroup_value = map[string]int32{
		"PRESET_GROUP_ID_VIDEO":     1000,
		"PRESET_GROUP_ID_PHOTO":     1001,
		"PRESET_GROUP_ID_TIMELAPSE": 1002,
		"PRESET_GROUP_ID_GENERAL":   2000,
	}
)

func (x EnumPresetGroup) Enum() *EnumPresetGroup {
	p := new(EnumPresetGroup)
	*p = x
	return p
}

func (x EnumPresetGroup) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumPresetGroup) Descriptor() protoreflect.EnumDescriptor {
	return file_preset_status_proto_enumTypes[1].Descriptor()
}

func (EnumPresetGroup) Type() protoreflect.EnumType {
	return &file_preset_status_proto_enumTypes[1]
}

func (x EnumPresetGroup) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumPresetGroup) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumPresetGroup(num)
	return nil
}

// Deprecated: Use EnumPresetGroup.Descriptor instead.
func (EnumPresetGroup) EnumDescriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{1}
}

type EnumPresetGroupIcon int32

const (
	EnumPresetGroupIcon_PRESET_GROUP_VIDEO_ICON_ID            EnumPresetGroupIcon = 0
	EnumPresetGroupIcon_PRESET_GROUP_PHOTO_ICON_ID            EnumPresetGroupIcon = 1
	EnumPresetGroupIcon_PRESET_GROUP_TIMELAPSE_ICON_ID        EnumPresetGroupIcon = 2
	EnumPresetGroupIcon_PRESET_GROUP_LONG_BAT_VIDEO_ICON_ID   EnumPresetGroupIcon = 3
	EnumPresetGroupIcon_PRESET_GROUP_ENDURANCE_VIDEO_ICON_ID  EnumPresetGroupIcon = 4
	EnumPresetGroupIcon_PRESET_GROUP_MAX_VIDEO_ICON_ID        EnumPresetGroupIcon = 5
	EnumPresetGroupIcon_PRESET_GROUP_MAX_PHOTO_ICON_ID        EnumPresetGroupIcon = 6
	EnumPresetGroupIcon_PRESET_GROUP_MAX_TIMELAPSE_ICON_ID    EnumPresetGroupIcon = 7
	EnumPresetGroupIcon_PRESET_GROUP_ND_MOD_VIDEO_ICON_ID     EnumPresetGroupIcon = 8
	EnumPresetGroupIcon_PRESET_GROUP_ND_MOD_PHOTO_ICON_ID     EnumPresetGroupIcon = 9
	EnumPresetGroupIcon_PRESET_GROUP_ND_MOD_TIMELAPSE_ICON_ID EnumPresetGroupIcon = 10
)

// Enum value maps for EnumPresetGroupIcon.
var (
	EnumPresetGroupIcon_name = map[int32]string{
		0:  "PRESET_GROUP_VIDEO_ICON_ID",
		1:  "PRESET_GROUP_PHOTO_ICON_ID",
		2:  "PRESET_GROUP_TIMELAPSE_ICON_ID",
		3:  "PRESET_GROUP_LONG_BAT_VIDEO_ICON_ID",
		4:  "PRESET_GROUP_ENDURANCE_VIDEO_ICON_ID",
		5:  "PRESET_GROUP_MAX_VIDEO_ICON_ID",
		6:  "PRESET_GROUP_MAX_PHOTO_ICON_ID",
		7:  "PRESET_GROUP_MAX_TIMELAPSE_ICON_ID",
		8:  "PRESET_GROUP_ND_MOD_VIDEO_ICON_ID",
		9:  "PRESET_GROUP_ND_MOD_PHOTO_ICON_ID",
		10: "PRESET_GROUP_ND_MOD_TIMELAPSE_ICON_ID",
	}
	EnumPresetGroupIcon_value = map[string]int32{
		"PRESET_GROUP_VIDEO_ICON_ID":            0,
		"PRESET_GROUP_PHOTO_ICON_ID":            1,
		"PRESET_GROUP_TIMELAPSE_ICON_ID":        2,
		"PRESET_GROUP_LONG_BAT_VIDEO_ICON_ID":   3,
		"PRESET_GROUP_ENDURANCE_VIDEO_ICON_ID":  4,
		"PRESET_GROUP_MAX_VIDEO_ICON_ID":        5,
		"PRESET_GROUP_MAX_PHOTO_ICON_ID":        6,
		"PRESET_GROUP_MAX_TIMELAPSE_ICON_ID":    7,
		"PRESET_GROUP_ND_MOD_VIDEO_ICON_ID":     8,
		"PRESET_GROUP_ND_MOD_PHOTO_ICON_ID":     9,
		"PRESET_GROUP_ND_MOD_TIMELAPSE_ICON_ID": 10,
	}
)

func (x EnumPresetGroupIcon) Enum() *EnumPresetGroupIcon {
	p := new(EnumPresetGroupIcon)
	*p = x
	return p
}

func (x EnumPresetGroupIcon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumPresetGroupIcon) Descriptor() protoreflect.EnumDescriptor {
	return file_preset_status_proto_enumTypes[2].Descriptor()
}

func (EnumPresetGroupIcon) Type() protoreflect.EnumType {
	return &file_preset_status_proto_enumTypes[2]
}

func (x EnumPresetGroupIcon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumPresetGroupIcon) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumPresetGroupIcon(num)
	return nil
}

// Deprecated: Use EnumPresetGroupIcon.Descriptor instead.
func (EnumPresetGroupIcon) EnumDescriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{2}
}

type EnumPresetIcon int32

const (
	EnumPresetIcon_PRESET_ICON_VIDEO                   EnumPresetIcon = 0
	EnumPresetIcon_PRESET_ICON_ACTIVITY                EnumPresetIcon = 1
	EnumPresetIcon_PRESET_ICON_CINEMATIC               EnumPresetIcon = 2
	EnumPresetIcon_PRESET_ICON_PHOTO                   EnumPresetIcon = 3
	EnumPresetIcon_PRESET_ICON_LIVE_BURST              EnumPresetIcon = 4
	EnumPresetIcon_PRESET_ICON_BURST                   EnumPresetIcon = 5
	EnumPresetIcon_PRESET_ICON_PHOTO_NIGHT             EnumPresetIcon = 6
	EnumPresetIcon_PRESET_ICON_TIMEWARP                EnumPresetIcon = 7
	EnumPresetIcon_PRESET_ICON_TIMELAPSE               EnumPresetIcon = 8
	EnumPresetIcon_PRESET_ICON_NIGHTLAPSE              EnumPresetIcon = 9
	EnumPresetIcon_PRESET_ICON_SNAIL                   EnumPresetIcon = 10
	EnumPresetIcon_PRESET_ICON_VIDEO_2                 EnumPresetIcon = 11
	EnumPresetIcon_PRESET_ICON_PHOTO_2                 EnumPresetIcon = 13
	EnumPresetIcon_PRESET_ICON_PANORAMA                EnumPresetIcon = 14
	EnumPresetIcon_PRESET_ICON_BURST_2                 EnumPresetIcon = 15
	EnumPresetIcon_PRESET_ICON_TIMEWARP_2              EnumPresetIcon = 16
	EnumPresetIcon_PRESET_ICON_TIMELAPSE_2             EnumPresetIcon = 17
	EnumPresetIcon_PRESET_ICON_CUSTOM                  EnumPresetIcon = 18
	EnumPresetIcon_PRESET_ICON_AIR                     EnumPresetIcon = 19
	EnumPresetIcon_PRESET_ICON_BIKE                    EnumPresetIcon = 20
	EnumPresetIcon_PRESET_ICON_EPIC                    EnumPresetIcon = 21
	EnumPresetIcon_PRESET_ICON_INDOOR                  EnumPresetIcon = 22
	EnumPresetIcon_PRESET_ICON_MOTOR                   EnumPresetIcon = 23
	EnumPresetIcon_PRESET_ICON_MOUNTED                 EnumPresetIcon = 24
	EnumPresetIcon_PRESET_ICON_OUTDOOR                 EnumPresetIcon = 25
	EnumPresetIcon_PRESET_ICON_POV                     EnumPresetIcon = 26
	EnumPresetIcon_PRESET_ICON_SELFIE                  EnumPresetIcon = 27
	EnumPresetIcon_PRESET_ICON_SKATE                   EnumPresetIcon = 28
	EnumPresetIcon_PRESET_ICON_SNOW                    EnumPresetIcon = 29
	EnumPresetIcon_PRESET_ICON_TRAIL                   EnumPresetIcon = 30
	EnumPresetIcon_PRESET_ICON_TRAVEL                  EnumPresetIcon = 31
	EnumPresetIcon_PRESET_ICON_WATER                   EnumPresetIcon = 32
	EnumPresetIcon_PRESET_ICON_LOOPING                 EnumPresetIcon = 33
	EnumPresetIcon_PRESET_ICON_STARS                   EnumPresetIcon = 34
	EnumPresetIcon_PRESET_ICON_ACTION                  EnumPresetIcon = 35
	EnumPresetIcon_PRESET_ICON_FOLLOW_CAM              EnumPresetIcon = 36
	EnumPresetIcon_PRESET_ICON_SURF                    EnumPresetIcon = 37
	EnumPresetIcon_PRESET_ICON_CITY                    EnumPresetIcon = 38
	EnumPresetIcon_PRESET_ICON_SHAKY                   EnumPresetIcon = 39
	EnumPresetIcon_PRESET_ICON_CHESTY                  EnumPresetIcon = 40
	EnumPresetIcon_PRESET_ICON_HELMET                  EnumPresetIcon = 41
	EnumPresetIcon_PRESET_ICON_BITE                    EnumPresetIcon = 42
	EnumPresetIcon_PRESET_ICON_CUSTOM_CINEMATIC        EnumPresetIcon = 43
	EnumPresetIcon_PRESET_ICON_VLOG                    EnumPresetIcon = 44
	EnumPresetIcon_PRESET_ICON_FPV                     EnumPresetIcon = 45
	EnumPresetIcon_PRESET_ICON_HDR                     EnumPresetIcon = 46
	EnumPresetIcon_PRESET_ICON_LANDSCAPE               EnumPresetIcon = 47
	EnumPresetIcon_PRESET_ICON_LOG                     EnumPresetIcon = 48
	EnumPresetIcon_PRESET_ICON_CUSTOM_SLOMO            EnumPresetIcon = 49
	EnumPresetIcon_PRESET_ICON_TRIPOD                  EnumPresetIcon = 50
	EnumPresetIcon_PRESET_ICON_MAX_VIDEO               EnumPresetIcon = 55
	EnumPresetIcon_PRESET_ICON_MAX_PHOTO               EnumPresetIcon = 56
	EnumPresetIcon_PRESET_ICON_MAX_TIMEWARP            EnumPresetIcon = 57
	EnumPresetIcon_PRESET_ICON_BASIC                   EnumPresetIcon = 58
	EnumPresetIcon_PRESET_ICON_ULTRA_SLO_MO            EnumPresetIcon = 59
	EnumPresetIcon_PRESET_ICON_STANDARD_ENDURANCE      EnumPresetIcon = 60
	EnumPresetIcon_PRESET_ICON_ACTIVITY_ENDURANCE      EnumPresetIcon = 61
	EnumPresetIcon_PRESET_ICON_CINEMATIC_ENDURANCE     EnumPresetIcon = 62
	EnumPresetIcon_PRESET_ICON_SLOMO_ENDURANCE         EnumPresetIcon = 63
	EnumPresetIcon_PRESET_ICON_STATIONARY_1            EnumPresetIcon = 64
	EnumPresetIcon_PRESET_ICON_STATIONARY_2            EnumPresetIcon = 65
	EnumPresetIcon_PRESET_ICON_STATIONARY_3            EnumPresetIcon = 66
	EnumPresetIcon_PRESET_ICON_STATIONARY_4            EnumPresetIcon = 67
	EnumPresetIcon_PRESET_ICON_SIMPLE_SUPER_PHOTO      EnumPresetIcon = 70
	EnumPresetIcon_PRESET_ICON_SIMPLE_NIGHT_PHOTO      EnumPresetIcon = 71
	EnumPresetIcon_PRESET_ICON_HIGHEST_QUALITY_VIDEO   EnumPresetIcon = 73
	EnumPresetIcon_PRESET_ICON_STANDARD_QUALITY_VIDEO  EnumPresetIcon = 74
	EnumPresetIcon_PRESET_ICON_BASIC_QUALITY_VIDEO     EnumPresetIcon = 75
	EnumPresetIcon_PRESET_ICON_STAR_TRAIL              EnumPresetIcon = 76
	EnumPresetIcon_PRESET_ICON_LIGHT_PAINTING          EnumPresetIcon = 77
	EnumPresetIcon_PRESET_ICON_LIGHT_TRAIL             EnumPresetIcon = 78
	EnumPresetIcon_PRESET_ICON_FULL_FRAME              EnumPresetIcon = 79
	EnumPresetIcon_PRESET_ICON_EASY_MAX_VIDEO          EnumPresetIcon = 80
	EnumPresetIcon_PRESET_ICON_EASY_MAX_PHOTO          EnumPresetIcon = 81
	EnumPresetIcon_PRESET_ICON_EASY_MAX_TIMEWARP       EnumPresetIcon = 82
	EnumPresetIcon_PRESET_ICON_EASY_MAX_STAR_TRAIL     EnumPresetIcon = 83
	EnumPresetIcon_PRESET_ICON_EASY_MAX_LIGHT_PAINTING EnumPresetIcon = 84
	EnumPresetIcon_PRESET_ICON_EASY_MAX_LIGHT_TRAIL    EnumPresetIcon = 85
	EnumPresetIcon_PRESET_ICON_MAX_STAR_TRAIL          EnumPresetIcon = 89
	EnumPresetIcon_PRESET_ICON_MAX_LIGHT_PAINTING      EnumPresetIcon = 90
	EnumPresetIcon_PRESET_ICON_MAX_LIGHT_TRAIL         EnumPresetIcon = 91
	EnumPresetIcon_PRESET_ICON_EASY_STANDARD_PROFILE   EnumPresetIcon = 100
	EnumPresetIcon_PRESET_ICON_EASY_HDR_PROFILE        EnumPresetIcon = 101
	EnumPresetIcon_PRESET_ICON_BURST_SLOMO             EnumPresetIcon = 102
	EnumPresetIcon_PRESET_ICON_TIMELAPSE_PHOTO         EnumPresetIcon = 1000
	EnumPresetIcon_PRESET_ICON_NIGHTLAPSE_PHOTO        EnumPresetIcon = 1001
)

// Enum value maps for EnumPresetIcon.
var (
	EnumPresetIcon_name = map[int32]string{
		0:    "PRESET_ICON_VIDEO",
		1:    "PRESET_ICON_ACTIVITY",
		2:    "PRESET_ICON_CINEMATIC",
		3:    "PRESET_ICON_PHOTO",
		4:    "PRESET_ICON_LIVE_BURST",
		5:    "PRESET_ICON_BURST",
		6:    "PRESET_ICON_PHOTO_NIGHT",
		7:    "PRESET_ICON_TIMEWARP",
		8:    "PRESET_ICON_TIMELAPSE",
		9:    "PRESET_ICON_NIGHTLAPSE",
		10:   "PRESET_ICON_SNAIL",
		11:   "PRESET_ICON_VIDEO_2",
		13:   "PRESET_ICON_PHOTO_2",
		14:   "PRESET_ICON_PANORAMA",
		15:   "PRESET_ICON_BURST_2",
		16:   "PRESET_ICON_TIMEWARP_2",
		17:   "PRESET_ICON_TIMELAPSE_2",
		18:   "PRESET_ICON_CUSTOM",
		19:   "PRESET_ICON_AIR",
		20:   "PRESET_ICON_BIKE",
		21:   "PRESET_ICON_EPIC",
		22:   "PRESET_ICON_INDOOR",
		23:   "PRESET_ICON_MOTOR",
		24:   "PRESET_ICON_MOUNTED",
		25:   "PRESET_ICON_OUTDOOR",
		26:   "PRESET_ICON_POV",
		27:   "PRESET_ICON_SELFIE",
		28:   "PRESET_ICON_SKATE",
		29:   "PRESET_ICON_SNOW",
		30:   "PRESET_ICON_TRAIL",
		31:   "PRESET_ICON_TRAVEL",
		32:   "PRESET_ICON_WATER",
		33:   "PRESET_ICON_LOOPING",
		34:   "PRESET_ICON_STARS",
		35:   "PRESET_ICON_ACTION",
		36:   "PRESET_ICON_FOLLOW_CAM",
		37:   "PRESET_ICON_SURF",
		38:   "PRESET_ICON_CITY",
		39:   "PRESET_ICON_SHAKY",
		40:   "PRESET_ICON_CHESTY",
		41:   "PRESET_ICON_HELMET",
		42:   "PRESET_ICON_BITE",
		43:   "PRESET_ICON_CUSTOM_CINEMATIC",
		44:   "PRESET_ICON_VLOG",
		45:   "PRESET_ICON_FPV",
		46:   "PRESET_ICON_HDR",
		47:   "PRESET_ICON_LANDSCAPE",
		48:   "PRESET_ICON_LOG",
		49:   "PRESET_ICON_CUSTOM_SLOMO",
		50:   "PRESET_ICON_TRIPOD",
		55:   "PRESET_ICON_MAX_VIDEO",
		56:   "PRESET_ICON_MAX_PHOTO",
		57:   "PRESET_ICON_MAX_TIMEWARP",
		58:   "PRESET_ICON_BASIC",
		59:   "PRESET_ICON_ULTRA_SLO_MO",
		60:   "PRESET_ICON_STANDARD_ENDURANCE",
		61:   "PRESET_ICON_ACTIVITY_ENDURANCE",
		62:   "PRESET_ICON_CINEMATIC_ENDURANCE",
		63:   "PRESET_ICON_SLOMO_ENDURANCE",
		64:   "PRESET_ICON_STATIONARY_1",
		65:   "PRESET_ICON_STATIONARY_2",
		66:   "PRESET_ICON_STATIONARY_3",
		67:   "PRESET_ICON_STATIONARY_4",
		70:   "PRESET_ICON_SIMPLE_SUPER_PHOTO",
		71:   "PRESET_ICON_SIMPLE_NIGHT_PHOTO",
		73:   "PRESET_ICON_HIGHEST_QUALITY_VIDEO",
		74:   "PRESET_ICON_STANDARD_QUALITY_VIDEO",
		75:   "PRESET_ICON_BASIC_QUALITY_VIDEO",
		76:   "PRESET_ICON_STAR_TRAIL",
		77:   "PRESET_ICON_LIGHT_PAINTING",
		78:   "PRESET_ICON_LIGHT_TRAIL",
		79:   "PRESET_ICON_FULL_FRAME",
		80:   "PRESET_ICON_EASY_MAX_VIDEO",
		81:   "PRESET_ICON_EASY_MAX_PHOTO",
		82:   "PRESET_ICON_EASY_MAX_TIMEWARP",
		83:   "PRESET_ICON_EASY_MAX_STAR_TRAIL",
		84:   "PRESET_ICON_EASY_MAX_LIGHT_PAINTING",
		85:   "PRESET_ICON_EASY_MAX_LIGHT_TRAIL",
		89:   "PRESET_ICON_MAX_STAR_TRAIL",
		90:   "PRESET_ICON_MAX_LIGHT_PAINTING",
		91:   "PRESET_ICON_MAX_LIGHT_TRAIL",
		100:  "PRESET_ICON_EASY_STANDARD_PROFILE",
		101:  "PRESET_ICON_EASY_HDR_PROFILE",
		102:  "PRESET_ICON_BURST_SLOMO",
		1000: "PRESET_ICON_TIMELAPSE_PHOTO",
		1001: "PRESET_ICON_NIGHTLAPSE_PHOTO",
	}
	EnumPresetIcon_value = map[string]int32{
		"PRESET_ICON_VIDEO":                   0,
		"PRESET_ICON_ACTIVITY":                1,
		"PRESET_ICON_CINEMATIC":               2,
		"PRESET_ICON_PHOTO":                   3,
		"PRESET_ICON_LIVE_BURST":              4,
		"PRESET_ICON_BURST":                   5,
		"PRESET_ICON_PHOTO_NIGHT":             6,
		"PRESET_ICON_TIMEWARP":                7,
		"PRESET_ICON_TIMELAPSE":               8,
		"PRESET_ICON_NIGHTLAPSE":              9,
		"PRESET_ICON_SNAIL":                   10,
		"PRESET_ICON_VIDEO_2":                 11,
		"PRESET_ICON_PHOTO_2":                 13,
		"PRESET_ICON_PANORAMA":                14,
		"PRESET_ICON_BURST_2":                 15,
		"PRESET_ICON_TIMEWARP_2":              16,
		"PRESET_ICON_TIMELAPSE_2":             17,
		"PRESET_ICON_CUSTOM":                  18,
		"PRESET_ICON_AIR":                     19,
		"PRESET_ICON_BIKE":                    20,
		"PRESET_ICON_EPIC":                    21,
		"PRESET_ICON_INDOOR":                  22,
		"PRESET_ICON_MOTOR":                   23,
		"PRESET_ICON_MOUNTED":                 24,
		"PRESET_ICON_OUTDOOR":                 25,
		"PRESET_ICON_POV":                     26,
		"PRESET_ICON_SELFIE":                  27,
		"PRESET_ICON_SKATE":                   28,
		"PRESET_ICON_SNOW":                    29,
		"PRESET_ICON_TRAIL":                   30,
		"PRESET_ICON_TRAVEL":                  31,
		"PRESET_ICON_WATER":                   32,
		"PRESET_ICON_LOOPING":                 33,
		"PRESET_ICON_STARS":                   34,
		"PRESET_ICON_ACTION":                  35,
		"PRESET_ICON_FOLLOW_CAM":              36,
		"PRESET_ICON_SURF":                    37,
		"PRESET_ICON_CITY":                    38,
		"PRESET_ICON_SHAKY":                   39,
		"PRESET_ICON_CHESTY":                  40,
		"PRESET_ICON_HELMET":                  41,
		"PRESET_ICON_BITE":                    42,
		"PRESET_ICON_CUSTOM_CINEMATIC":        43,
		"PRESET_ICON_VLOG":                    44,
		"PRESET_ICON_FPV":                     45,
		"PRESET_ICON_HDR":                     46,
		"PRESET_ICON_LANDSCAPE":               47,
		"PRESET_ICON_LOG":                     48,
		"PRESET_ICON_CUSTOM_SLOMO":            49,
		"PRESET_ICON_TRIPOD":                  50,
		"PRESET_ICON_MAX_VIDEO":               55,
		"PRESET_ICON_MAX_PHOTO":               56,
		"PRESET_ICON_MAX_TIMEWARP":            57,
		"PRESET_ICON_BASIC":                   58,
		"PRESET_ICON_ULTRA_SLO_MO":            59,
		"PRESET_ICON_STANDARD_ENDURANCE":      60,
		"PRESET_ICON_ACTIVITY_ENDURANCE":      61,
		"PRESET_ICON_CINEMATIC_ENDURANCE":     62,
		"PRESET_ICON_SLOMO_ENDURANCE":         63,
		"PRESET_ICON_STATIONARY_1":            64,
		"PRESET_ICON_STATIONARY_2":            65,
		"PRESET_ICON_STATIONARY_3":            66,
		"PRESET_ICON_STATIONARY_4":            67,
		"PRESET_ICON_SIMPLE_SUPER_PHOTO":      70,
		"PRESET_ICON_SIMPLE_NIGHT_PHOTO":      71,
		"PRESET_ICON_HIGHEST_QUALITY_VIDEO":   73,
		"PRESET_ICON_STANDARD_QUALITY_VIDEO":  74,
		"PRESET_ICON_BASIC_QUALITY_VIDEO":     75,
		"PRESET_ICON_STAR_TRAIL":              76,
		"PRESET_ICON_LIGHT_PAINTING":          77,
		"PRESET_ICON_LIGHT_TRAIL":             78,
		"PRESET_ICON_FULL_FRAME":              79,
		"PRESET_ICON_EASY_MAX_VIDEO":          80,
		"PRESET_ICON_EASY_MAX_PHOTO":          81,
		"PRESET_ICON_EASY_MAX_TIMEWARP":       82,
		"PRESET_ICON_EASY_MAX_STAR_TRAIL":     83,
		"PRESET_ICON_EASY_MAX_LIGHT_PAINTING": 84,
		"PRESET_ICON_EASY_MAX_LIGHT_TRAIL":    85,
		"PRESET_ICON_MAX_STAR_TRAIL":          89,
		"PRESET_ICON_MAX_LIGHT_PAINTING":      90,
		"PRESET_ICON_MAX_LIGHT_TRAIL":         91,
		"PRESET_ICON_EASY_STANDARD_PROFILE":   100,
		"PRESET_ICON_EASY_HDR_PROFILE":        101,
		"PRESET_ICON_BURST_SLOMO":             102,
		"PRESET_ICON_TIMELAPSE_PHOTO":         1000,
		"PRESET_ICON_NIGHTLAPSE_PHOTO":        1001,
	}
)

func (x EnumPresetIcon) Enum() *EnumPresetIcon {
	p := new(EnumPresetIcon)
	*p = x
	return p
}

func (x EnumPresetIcon) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumPresetIcon) Descriptor() protoreflect.EnumDescriptor {
	return file_preset_status_proto_enumTypes[3].Descriptor()
}

func (EnumPresetIcon) Type() protoreflect.EnumType {
	return &file_preset_status_proto_enumTypes[3]
}

func (x EnumPresetIcon) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumPresetIcon) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumPresetIcon(num)
	return nil
}

// Deprecated: Use EnumPresetIcon.Descriptor instead.
func (EnumPresetIcon) EnumDescriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{3}
}

type EnumPresetTitle int32

const (
	EnumPresetTitle_PRESET_TITLE_ACTIVITY                 EnumPresetTitle = 0
	EnumPresetTitle_PRESET_TITLE_STANDARD                 EnumPresetTitle = 1
	EnumPresetTitle_PRESET_TITLE_CINEMATIC                EnumPresetTitle = 2
	EnumPresetTitle_PRESET_TITLE_PHOTO                    EnumPresetTitle = 3
	EnumPresetTitle_PRESET_TITLE_LIVE_BURST               EnumPresetTitle = 4
	EnumPresetTitle_PRESET_TITLE_BURST                    EnumPresetTitle = 5
	EnumPresetTitle_PRESET_TITLE_NIGHT                    EnumPresetTitle = 6
	EnumPresetTitle_PRESET_TITLE_TIME_WARP                EnumPresetTitle = 7
	EnumPresetTitle_PRESET_TITLE_TIME_LAPSE               EnumPresetTitle = 8
	EnumPresetTitle_PRESET_TITLE_NIGHT_LAPSE              EnumPresetTitle = 9
	EnumPresetTitle_PRESET_TITLE_VIDEO                    EnumPresetTitle = 10
	EnumPresetTitle_PRESET_TITLE_SLOMO                    EnumPresetTitle = 11
	EnumPresetTitle_PRESET_TITLE_PHOTO_2                  EnumPresetTitle = 13
	EnumPresetTitle_PRESET_TITLE_PANORAMA                 EnumPresetTitle = 14
	EnumPresetTitle_PRESET_TITLE_TIME_WARP_2              EnumPresetTitle = 16
	EnumPresetTitle_PRESET_TITLE_CUSTOM                   EnumPresetTitle = 18
	EnumPresetTitle_PRESET_TITLE_AIR                      EnumPresetTitle = 19
	EnumPresetTitle_PRESET_TITLE_BIKE                     EnumPresetTitle = 20
	EnumPresetTitle_PRESET_TITLE_EPIC                     EnumPresetTitle = 21
	EnumPresetTitle_PRESET_TITLE_INDOOR                   EnumPresetTitle = 22
	EnumPresetTitle_PRESET_TITLE_MOTOR                    EnumPresetTitle = 23
	EnumPresetTitle_PRESET_TITLE_MOUNTED                  EnumPresetTitle = 24
	EnumPresetTitle_PRESET_TITLE_OUTDOOR                  EnumPresetTitle = 25
	EnumPresetTitle_PRESET_TITLE_POV                      EnumPresetTitle = 26
	EnumPresetTitle_PRESET_TITLE_SELFIE                   EnumPresetTitle = 27
	EnumPresetTitle_PRESET_TITLE_SKATE                    EnumPresetTitle = 28
	EnumPresetTitle_PRESET_TITLE_SNOW                     EnumPresetTitle = 29
	EnumPresetTitle_PRESET_TITLE_TRAIL                    EnumPresetTitle = 30
	EnumPresetTitle_PRESET_TITLE_TRAVEL                   EnumPresetTitle = 31
	EnumPresetTitle_PRESET_TITLE_WATER                    EnumPresetTitle = 32
	EnumPresetTitle_PRESET_TITLE_LOOPING                  EnumPresetTitle = 33
	EnumPresetTitle_PRESET_TITLE_STARS                    EnumPresetTitle = 34
	EnumPresetTitle_PRESET_TITLE_ACTION                   EnumPresetTitle = 35
	EnumPresetTitle_PRESET_TITLE_FOLLOW_CAM               EnumPresetTitle = 36
	EnumPresetTitle_PRESET_TITLE_SURF                     EnumPresetTitle = 37
	EnumPresetTitle_PRESET_TITLE_CITY                     EnumPresetTitle = 38
	EnumPresetTitle_PRESET_TITLE_SHAKY                    EnumPresetTitle = 39
	EnumPresetTitle_PRESET_TITLE_CHESTY                   EnumPresetTitle = 40
	EnumPresetTitle_PRESET_TITLE_HELMET                   EnumPresetTitle = 41
	EnumPresetTitle_PRESET_TITLE_BITE                     EnumPresetTitle = 42
	EnumPresetTitle_PRESET_TITLE_CUSTOM_CINEMATIC         EnumPresetTitle = 43
	EnumPresetTitle_PRESET_TITLE_VLOG                     EnumPresetTitle = 44
	EnumPresetTitle_PRESET_TITLE_FPV                      EnumPresetTitle = 45
	EnumPresetTitle_PRESET_TITLE_HDR                      EnumPresetTitle = 46
	EnumPresetTitle_PRESET_TITLE_LANDSCAPE                EnumPresetTitle = 47
	EnumPresetTitle_PRESET_TITLE_LOG                      EnumPresetTitle = 48
	EnumPresetTitle_PRESET_TITLE_CUSTOM_SLOMO             EnumPresetTitle = 49
	EnumPresetTitle_PRESET_TITLE_TRIPOD                   EnumPresetTitle = 50
	EnumPresetTitle_PRESET_TITLE_BASIC                    EnumPresetTitle = 58
	EnumPresetTitle_PRESET_TITLE_ULTRA_SLO_MO             EnumPresetTitle = 59
	EnumPresetTitle_PRESET_TITLE_STANDARD_ENDURANCE       EnumPresetTitle = 60
	EnumPresetTitle_PRESET_TITLE_ACTIVITY_ENDURANCE       EnumPresetTitle = 61
	EnumPresetTitle_PRESET_TITLE_CINEMATIC_ENDURANCE      EnumPresetTitle = 62
	EnumPresetTitle_PRESET_TITLE_SLOMO_ENDURANCE          EnumPresetTitle = 63
	EnumPresetTitle_PRESET_TITLE_STATIONARY_1             EnumPresetTitle = 64
	EnumPresetTitle_PRESET_TITLE_STATIONARY_2             EnumPresetTitle = 65
	EnumPresetTitle_PRESET_TITLE_STATIONARY_3             EnumPresetTitle = 66
	EnumPresetTitle_PRESET_TITLE_STATIONARY_4             EnumPresetTitle = 67
	EnumPresetTitle_PRESET_TITLE_SIMPLE_VIDEO             EnumPresetTitle = 68
	EnumPresetTitle_PRESET_TITLE_SIMPLE_TIME_WARP         EnumPresetTitle = 69
	EnumPresetTitle_PRESET_TITLE_SIMPLE_SUPER_PHOTO       EnumPresetTitle = 70
	EnumPresetTitle_PRESET_TITLE_SIMPLE_NIGHT_PHOTO       EnumPresetTitle = 71
	EnumPresetTitle_PRESET_TITLE_SIMPLE_VIDEO_ENDURANCE   EnumPresetTitle = 72
	EnumPresetTitle_PRESET_TITLE_HIGHEST_QUALITY          EnumPresetTitle = 73
	EnumPresetTitle_PRESET_TITLE_EXTENDED_BATTERY         EnumPresetTitle = 74
	EnumPresetTitle_PRESET_TITLE_LONGEST_BATTERY          EnumPresetTitle = 75
	EnumPresetTitle_PRESET_TITLE_STAR_TRAIL               EnumPresetTitle = 76
	EnumPresetTitle_PRESET_TITLE_LIGHT_PAINTING           EnumPresetTitle = 77
	EnumPresetTitle_PRESET_TITLE_LIGHT_TRAIL              EnumPresetTitle = 78
	EnumPresetTitle_PRESET_TITLE_FULL_FRAME               EnumPresetTitle = 79
	EnumPresetTitle_PRESET_TITLE_STANDARD_QUALITY_VIDEO   EnumPresetTitle = 82
	EnumPresetTitle_PRESET_TITLE_BASIC_QUALITY_VIDEO      EnumPresetTitle = 83
	EnumPresetTitle_PRESET_TITLE_HIGHEST_QUALITY_VIDEO    EnumPresetTitle = 93
	EnumPresetTitle_PRESET_TITLE_USER_DEFINED_CUSTOM_NAME EnumPresetTitle = 94
	EnumPresetTitle_PRESET_TITLE_EASY_STANDARD_PROFILE    EnumPresetTitle = 99
	EnumPresetTitle_PRESET_TITLE_EASY_HDR_PROFILE         EnumPresetTitle = 100
	EnumPresetTitle_PRESET_TITLE_BURST_SLOMO              EnumPresetTitle = 106
	EnumPresetTitle_PRESET_TITLE_4_3_VIDEO                EnumPresetTitle = 125
	EnumPresetTitle_PRESET_TITLE_16_9_VIDEO               EnumPresetTitle = 126
	EnumPresetTitle_PRESET_TITLE_16_9_SLOMO               EnumPresetTitle = 127
	EnumPresetTitle_PRESET_TITLE_TIME_LAPSE_VIDEO         EnumPresetTitle = 131
	EnumPresetTitle_PRESET_TITLE_TIME_LAPSE_PHOTO         EnumPresetTitle = 132
	EnumPresetTitle_PRESET_TITLE_NIGHT_LAPSE_VIDEO        EnumPresetTitle = 133
	EnumPresetTitle_PRESET_TITLE_NIGHT_LAPSE_PHOTO        EnumPresetTitle = 134
)

// Enum value maps for EnumPresetTitle.
var (
	EnumPresetTitle_name = map[int32]string{
		0:   "PRESET_TITLE_ACTIVITY",
		1:   "PRESET_TITLE_STANDARD",
		2:   "PRESET_TITLE_CINEMATIC",
		3:   "PRESET_TITLE_PHOTO",
		4:   "PRESET_TITLE_LIVE_BURST",
		5:   "PRESET_TITLE_BURST",
		6:   "PRESET_TITLE_NIGHT",
		7:   "PRESET_TITLE_TIME_WARP",
		8:   "PRESET_TITLE_TIME_LAPSE",
		9:   "PRESET_TITLE_NIGHT_LAPSE",
		10:  "PRESET_TITLE_VIDEO",
		11:  "PRESET_TITLE_SLOMO",
		13:  "PRESET_TITLE_PHOTO_2",
		14:  "PRESET_TITLE_PANORAMA",
		16:  "PRESET_TITLE_TIME_WARP_2",
		18:  "PRESET_TITLE_CUSTOM",
		19:  "PRESET_TITLE_AIR",
		20:  "PRESET_TITLE_BIKE",
		21:  "PRESET_TITLE_EPIC",
		22:  "PRESET_TITLE_INDOOR",
		23:  "PRESET_TITLE_MOTOR",
		24:  "PRESET_TITLE_MOUNTED",
		25:  "PRESET_TITLE_OUTDOOR",
		26:  "PRESET_TITLE_POV",
		27:  "PRESET_TITLE_SELFIE",
		28:  "PRESET_TITLE_SKATE",
		29:  "PRESET_TITLE_SNOW",
		30:  "PRESET_TITLE_TRAIL",
		31:  "PRESET_TITLE_TRAVEL",
		32:  "PRESET_TITLE_WATER",
		33:  "PRESET_TITLE_LOOPING",
		34:  "PRESET_TITLE_STARS",
		35:  "PRESET_TITLE_ACTION",
		36:  "PRESET_TITLE_FOLLOW_CAM",
		37:  "PRESET_TITLE_SURF",
		38:  "PRESET_TITLE_CITY",
		39:  "PRESET_TITLE_SHAKY",
		40:  "PRESET_TITLE_CHESTY",
		41:  "PRESET_TITLE_HELMET",
		42:  "PRESET_TITLE_BITE",
		43:  "PRESET_TITLE_CUSTOM_CINEMATIC",
		44:  "PRESET_TITLE_VLOG",
		45:  "PRESET_TITLE_FPV",
		46:  "PRESET_TITLE_HDR",
		47:  "PRESET_TITLE_LANDSCAPE",
		48:  "PRESET_TITLE_LOG",
		49:  "PRESET_TITLE_CUSTOM_SLOMO",
		50:  "PRESET_TITLE_TRIPOD",
		58:  "PRESET_TITLE_BASIC",
		59:  "PRESET_TITLE_ULTRA_SLO_MO",
		60:  "PRESET_TITLE_STANDARD_ENDURANCE",
		61:  "PRESET_TITLE_ACTIVITY_ENDURANCE",
		62:  "PRESET_TITLE_CINEMATIC_ENDURANCE",
		63:  "PRESET_TITLE_SLOMO_ENDURANCE",
		64:  "PRESET_TITLE_STATIONARY_1",
		65:  "PRESET_TITLE_STATIONARY_2",
		66:  "PRESET_TITLE_STATIONARY_3",
		67:  "PRESET_TITLE_STATIONARY_4",
		68:  "PRESET_TITLE_SIMPLE_VIDEO",
		69:  "PRESET_TITLE_SIMPLE_TIME_WARP",
		70:  "PRESET_TITLE_SIMPLE_SUPER_PHOTO",
		71:  "PRESET_TITLE_SIMPLE_NIGHT_PHOTO",
		72:  "PRESET_TITLE_SIMPLE_VIDEO_ENDURANCE",
		73:  "PRESET_TITLE_HIGHEST_QUALITY",
		74:  "PRESET_TITLE_EXTENDED_BATTERY",
		75:  "PRESET_TITLE_LONGEST_BATTERY",
		76:  "PRESET_TITLE_STAR_TRAIL",
		77:  "PRESET_TITLE_LIGHT_PAINTING",
		78:  "PRESET_TITLE_LIGHT_TRAIL",
		79:  "PRESET_TITLE_FULL_FRAME",
		82:  "PRESET_TITLE_STANDARD_QUALITY_VIDEO",
		83:  "PRESET_TITLE_BASIC_QUALITY_VIDEO",
		93:  "PRESET_TITLE_HIGHEST_QUALITY_VIDEO",
		94:  "PRESET_TITLE_USER_DEFINED_CUSTOM_NAME",
		99:  "PRESET_TITLE_EASY_STANDARD_PROFILE",
		100: "PRESET_TITLE_EASY_HDR_PROFILE",
		106: "PRESET_TITLE_BURST_SLOMO",
		125: "PRESET_TITLE_4_3_VIDEO",
		126: "PRESET_TITLE_16_9_VIDEO",
		127: "PRESET_TITLE_16_9_SLOMO",
		131: "PRESET_TITLE_TIME_LAPSE_VIDEO",
		132: "PRESET_TITLE_TIME_LAPSE_PHOTO",
		133: "PRESET_TITLE_NIGHT_LAPSE_VIDEO",
		134: "PRESET_TITLE_NIGHT_LAPSE_PHOTO",
	}
	EnumPresetTitle_value = map[string]int32{
		"PRESET_TITLE_ACTIVITY":                 0,
		"PRESET_TITLE_STANDARD":                 1,
		"PRESET_TITLE_CINEMATIC":                2,
		"PRESET_TITLE_PHOTO":                    3,
		"PRESET_TITLE_LIVE_BURST":               4,
		"PRESET_TITLE_BURST":                    5,
		"PRESET_TITLE_NIGHT":                    6,
		"PRESET_TITLE_TIME_WARP":                7,
		"PRESET_TITLE_TIME_LAPSE":               8,
		"PRESET_TITLE_NIGHT_LAPSE":              9,
		"PRESET_TITLE_VIDEO":                    10,
		"PRESET_TITLE_SLOMO":                    11,
		"PRESET_TITLE_PHOTO_2":                  13,
		"PRESET_TITLE_PANORAMA":                 14,
		"PRESET_TITLE_TIME_WARP_2":              16,
		"PRESET_TITLE_CUSTOM":                   18,
		"PRESET_TITLE_AIR":                      19,
		"PRESET_TITLE_BIKE":                     20,
		"PRESET_TITLE_EPIC":                     21,
		"PRESET_TITLE_INDOOR":                   22,
		"PRESET_TITLE_MOTOR":                    23,
		"PRESET_TITLE_MOUNTED":                  24,
		"PRESET_TITLE_OUTDOOR":                  25,
		"PRESET_TITLE_POV":                      26,
		"PRESET_TITLE_SELFIE":                   27,
		"PRESET_TITLE_SKATE":                    28,
		"PRESET_TITLE_SNOW":                     29,
		"PRESET_TITLE_TRAIL":                    30,
		"PRESET_TITLE_TRAVEL":                   31,
		"PRESET_TITLE_WATER":                    32,
		"PRESET_TITLE_LOOPING":                  33,
		"PRESET_TITLE_STARS":                    34,
		"PRESET_TITLE_ACTION":                   35,
		"PRESET_TITLE_FOLLOW_CAM":               36,
		"PRESET_TITLE_SURF":                     37,
		"PRESET_TITLE_CITY":                     38,
		"PRESET_TITLE_SHAKY":                    39,
		"PRESET_TITLE_CHESTY":                   40,
		"PRESET_TITLE_HELMET":                   41,
		"PRESET_TITLE_BITE":                     42,
		"PRESET_TITLE_CUSTOM_CINEMATIC":         43,
		"PRESET_TITLE_VLOG":                     44,
		"PRESET_TITLE_FPV":                      45,
		"PRESET_TITLE_HDR":                      46,
		"PRESET_TITLE_LANDSCAPE":                47,
		"PRESET_TITLE_LOG":                      48,
		"PRESET_TITLE_CUSTOM_SLOMO":             49,
		"PRESET_TITLE_TRIPOD":                   50,
		"PRESET_TITLE_BASIC":                    58,
		"PRESET_TITLE_ULTRA_SLO_MO":             59,
		"PRESET_TITLE_STANDARD_ENDURANCE":       60,
		"PRESET_TITLE_ACTIVITY_ENDURANCE":       61,
		"PRESET_TITLE_CINEMATIC_ENDURANCE":      62,
		"PRESET_TITLE_SLOMO_ENDURANCE":          63,
		"PRESET_TITLE_STATIONARY_1":             64,
		"PRESET_TITLE_STATIONARY_2":             65,
		"PRESET_TITLE_STATIONARY_3":             66,
		"PRESET_TITLE_STATIONARY_4":             67,
		"PRESET_TITLE_SIMPLE_VIDEO":             68,
		"PRESET_TITLE_SIMPLE_TIME_WARP":         69,
		"PRESET_TITLE_SIMPLE_SUPER_PHOTO":       70,
		"PRESET_TITLE_SIMPLE_NIGHT_PHOTO":       71,
		"PRESET_TITLE_SIMPLE_VIDEO_ENDURANCE":   72,
		"PRESET_TITLE_HIGHEST_QUALITY":          73,
		"PRESET_TITLE_EXTENDED_BATTERY":         74,
		"PRESET_TITLE_LONGEST_BATTERY":          75,
		"PRESET_TITLE_STAR_TRAIL":               76,
		"PRESET_TITLE_LIGHT_PAINTING":           77,
		"PRESET_TITLE_LIGHT_TRAIL":              78,
		"PRESET_TITLE_FULL_FRAME":               79,
		"PRESET_TITLE_STANDARD_QUALITY_VIDEO":   82,
		"PRESET_TITLE_BASIC_QUALITY_VIDEO":      83,
		"PRESET_TITLE_HIGHEST_QUALITY_VIDEO":    93,
		"PRESET_TITLE_USER_DEFINED_CUSTOM_NAME": 94,
		"PRESET_TITLE_EASY_STANDARD_PROFILE":    99,
		"PRESET_TITLE_EASY_HDR_PROFILE":         100,
		"PRESET_TITLE_BURST_SLOMO":              106,
		"PRESET_TITLE_4_3_VIDEO":                125,
		"PRESET_TITLE_16_9_VIDEO":               126,
		"PRESET_TITLE_16_9_SLOMO":               127,
		"PRESET_TITLE_TIME_LAPSE_VIDEO":         131,
		"PRESET_TITLE_TIME_LAPSE_PHOTO":         132,
		"PRESET_TITLE_NIGHT_LAPSE_VIDEO":        133,
		"PRESET_TITLE_NIGHT_LAPSE_PHOTO":        134,
	}
)

func (x EnumPresetTitle) Enum() *EnumPresetTitle {
	p := new(EnumPresetTitle)
	*p = x
	return p
}

func (x EnumPresetTitle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumPresetTitle) Descriptor() protoreflect.EnumDescriptor {
	return file_preset_status_proto_enumTypes[4].Descriptor()
}

func (EnumPresetTitle) Type() protoreflect.EnumType {
	return &file_preset_status_proto_enumTypes[4]
}

func (x EnumPresetTitle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumPresetTitle) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumPresetTitle(num)
	return nil
}

// Deprecated: Use EnumPresetTitle.Descriptor instead.
func (EnumPresetTitle) EnumDescriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{4}
}

// *
// Current Preset status
//
// Sent either:
//
// - Synchronously via initial response to @ref RequestGetPresetStatus
// - Asynchronously when Preset change if registered in @ref RequestGetPresetStatus
type NotifyPresetStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PresetGroupArray []*PresetGroup         `protobuf:"bytes,1,rep,name=preset_group_array,json=presetGroupArray" json:"preset_group_array,omitempty"` // List of currently available Preset Groups
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NotifyPresetStatus) Reset() {
	*x = NotifyPresetStatus{}
	mi := &file_preset_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyPresetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyPresetStatus) ProtoMessage() {}

func (x *NotifyPresetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_preset_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyPresetStatus.ProtoReflect.Descriptor instead.
func (*NotifyPresetStatus) Descriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyPresetStatus) GetPresetGroupArray() []*PresetGroup {
	if x != nil {
		return x.PresetGroupArray
	}
	return nil
}

// *
// An individual preset.
type Preset struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                                                          // Preset ID
	Mode         *EnumFlatMode          `protobuf:"varint,2,opt,name=mode,enum=open_gopro.EnumFlatMode" json:"mode,omitempty"`                         // Preset flatmode ID
	TitleId      *EnumPresetTitle       `protobuf:"varint,3,opt,name=title_id,json=titleId,enum=open_gopro.EnumPresetTitle" json:"title_id,omitempty"` // Preset Title ID
	TitleNumber  *int32                 `protobuf:"varint,4,opt,name=title_number,json=titleNumber" json:"title_number,omitempty"`                     // Preset Title Number (e.g. 1/2/3 in Custom1, Custom2, Custom3)
	UserDefined  *bool                  `protobuf:"varint,5,opt,name=user_defined,json=userDefined" json:"user_defined,omitempty"`                     // Is the Preset custom/user-defined?
	Icon         *EnumPresetIcon        `protobuf:"varint,6,opt,name=icon,enum=open_gopro.EnumPresetIcon" json:"icon,omitempty"`                       // Preset Icon ID
	SettingArray []*PresetSetting       `protobuf:"bytes,7,rep,name=setting_array,json=settingArray" json:"setting_array,omitempty"`                   // Array of settings associated with this Preset
	IsModified   *bool                  `protobuf:"varint,8,opt,name=is_modified,json=isModified" json:"is_modified,omitempty"`                        // Has Preset been modified from factory defaults? (False for user-defined Presets)
	IsFixed      *bool                  `protobuf:"varint,9,opt,name=is_fixed,json=isFixed" json:"is_fixed,omitempty"`                                 // Is this Preset mutable?
	CustomName   *string                `protobuf:"bytes,10,opt,name=custom_name,json=customName" json:"custom_name,omitempty"`                        // Custom string name given to this preset via @ref RequestCustomPresetUpdate
	// *
	// Is the preset currently visible in the camera UI?
	//
	// Note that a Preset's UI visibility can be set with @ref RequestPresetSetVisibility
	IsVisible     *bool `protobuf:"varint,11,opt,name=is_visible,json=isVisible" json:"is_visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_preset_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_preset_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{1}
}

func (x *Preset) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Preset) GetMode() EnumFlatMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return EnumFlatMode_FLAT_MODE_UNKNOWN
}

func (x *Preset) GetTitleId() EnumPresetTitle {
	if x != nil && x.TitleId != nil {
		return *x.TitleId
	}
	return EnumPresetTitle_PRESET_TITLE_ACTIVITY
}

func (x *Preset) GetTitleNumber() int32 {
	if x != nil && x.TitleNumber != nil {
		return *x.TitleNumber
	}
	return 0
}

func (x *Preset) GetUserDefined() bool {
	if x != nil && x.UserDefined != nil {
		return *x.UserDefined
	}
	return false
}

func (x *Preset) GetIcon() EnumPresetIcon {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return EnumPresetIcon_PRESET_ICON_VIDEO
}

func (x *Preset) GetSettingArray() []*PresetSetting {
	if x != nil {
		return x.SettingArray
	}
	return nil
}

func (x *Preset) GetIsModified() bool {
	if x != nil && x.IsModified != nil {
		return *x.IsModified
	}
	return false
}

func (x *Preset) GetIsFixed() bool {
	if x != nil && x.IsFixed != nil {
		return *x.IsFixed
	}
	return false
}

func (x *Preset) GetCustomName() string {
	if x != nil && x.CustomName != nil {
		return *x.CustomName
	}
	return ""
}

func (x *Preset) GetIsVisible() bool {
	if x != nil && x.IsVisible != nil {
		return *x.IsVisible
	}
	return false
}

// *
// Request to Update the Title and / or Icon of the Active Custom Preset
//
// This only operates on the currently active Preset and will fail  if the current
// Preset is not custom.
//
// The use cases are:
//
// 1. Update the Custom Preset Icon
//
//   - `icon_id` is always optional and can always be passed
//
// and / or
//
// 2. Update the Custom Preset Title to a...
//
//   - **Factory Preset Title**: Set `title_id` to a non-PRESET_TITLE_USER_DEFINED_CUSTOM_NAME (94) value
//   - **Custom Preset Name**: Set `title_id` to PRESET_TITLE_USER_DEFINED_CUSTOM_NAME (94) and specify a `custom_name`
//
// Returns a @ref ResponseGeneric with the status of the preset update request.
type RequestCustomPresetUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *
	// Preset Title ID
	//
	// The range of acceptable custom title ID's can be found in the initial @ref NotifyPresetStatus response
	// to @ref RequestGetPresetStatus
	TitleId *EnumPresetTitle `protobuf:"varint,1,opt,name=title_id,json=titleId,enum=open_gopro.EnumPresetTitle" json:"title_id,omitempty"`
	// *
	// UTF-8 encoded custom preset name to be used if `title_id` is set to 94 (PRESET_TITLE_USER_DEFINED_CUSTOM_NAME)
	//
	// The name must obey the following:
	//
	//   - Custom titles must be between 1 and 16 characters (inclusive)
	//   - No special characters outside of the following languages: English, French, Italian, German,
	//     Spanish, Portuguese, Swedish, Russian
	CustomName *string `protobuf:"bytes,2,opt,name=custom_name,json=customName" json:"custom_name,omitempty"`
	// *
	// Preset Icon ID
	//
	// The range of acceptable custom icon ID's can be found in the initial @ref NotifyPresetStatus response to
	// @ref RequestGetPresetStatus
	IconId        *EnumPresetIcon `protobuf:"varint,3,opt,name=icon_id,json=iconId,enum=open_gopro.EnumPresetIcon" json:"icon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCustomPresetUpdate) Reset() {
	*x = RequestCustomPresetUpdate{}
	mi := &file_preset_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCustomPresetUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCustomPresetUpdate) ProtoMessage() {}

func (x *RequestCustomPresetUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_preset_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCustomPresetUpdate.ProtoReflect.Descriptor instead.
func (*RequestCustomPresetUpdate) Descriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{2}
}

func (x *RequestCustomPresetUpdate) GetTitleId() EnumPresetTitle {
	if x != nil && x.TitleId != nil {
		return *x.TitleId
	}
	return EnumPresetTitle_PRESET_TITLE_ACTIVITY
}

func (x *RequestCustomPresetUpdate) GetCustomName() string {
	if x != nil && x.CustomName != nil {
		return *x.CustomName
	}
	return ""
}

func (x *RequestCustomPresetUpdate) GetIconId() EnumPresetIcon {
	if x != nil && x.IconId != nil {
		return *x.IconId
	}
	return EnumPresetIcon_PRESET_ICON_VIDEO
}

// *
// Set Preset UI Visibility
//
// Shows or hides a Preset in the camera UI.
//
// Note that a Preset's visibility determines how it is returned as part of the @ref RequestGetPresetStatus response
//
// Returns a @ref ResponseGeneric with the status of the preset update request.
type RequestPresetSetVisibility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`           // preset ID to operate on
	Visible       *bool                  `protobuf:"varint,2,opt,name=visible" json:"visible,omitempty"` // True to set the preset visible, False to hide the preset.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPresetSetVisibility) Reset() {
	*x = RequestPresetSetVisibility{}
	mi := &file_preset_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPresetSetVisibility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPresetSetVisibility) ProtoMessage() {}

func (x *RequestPresetSetVisibility) ProtoReflect() protoreflect.Message {
	mi := &file_preset_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPresetSetVisibility.ProtoReflect.Descriptor instead.
func (*RequestPresetSetVisibility) Descriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{3}
}

func (x *RequestPresetSetVisibility) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *RequestPresetSetVisibility) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

// Preset Group meta information and contained Presets
type PresetGroup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *EnumPresetGroup       `protobuf:"varint,1,opt,name=id,enum=open_gopro.EnumPresetGroup" json:"id,omitempty"`                             // Preset Group ID
	PresetArray    []*Preset              `protobuf:"bytes,2,rep,name=preset_array,json=presetArray" json:"preset_array,omitempty"`                         // Array of Presets contained in this Preset Group
	CanAddPreset   *bool                  `protobuf:"varint,3,opt,name=can_add_preset,json=canAddPreset" json:"can_add_preset,omitempty"`                   // Is there room in the group to add additional Presets?
	Icon           *EnumPresetGroupIcon   `protobuf:"varint,4,opt,name=icon,enum=open_gopro.EnumPresetGroupIcon" json:"icon,omitempty"`                     // The icon to display for this preset group
	ModeArray      []EnumFlatMode         `protobuf:"varint,5,rep,name=mode_array,json=modeArray,enum=open_gopro.EnumFlatMode" json:"mode_array,omitempty"` // A list of flatmodes available for this preset group
	CustomName     *string                `protobuf:"bytes,6,opt,name=custom_name,json=customName" json:"custom_name,omitempty"`                            // Custom string name given to this preset group
	ActivePresetId *int32                 `protobuf:"varint,7,opt,name=active_preset_id,json=activePresetId" json:"active_preset_id,omitempty"`             // Active preset id in this group
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresetGroup) Reset() {
	*x = PresetGroup{}
	mi := &file_preset_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetGroup) ProtoMessage() {}

func (x *PresetGroup) ProtoReflect() protoreflect.Message {
	mi := &file_preset_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetGroup.ProtoReflect.Descriptor instead.
func (*PresetGroup) Descriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{4}
}

func (x *PresetGroup) GetId() EnumPresetGroup {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return EnumPresetGroup_PRESET_GROUP_ID_VIDEO
}

func (x *PresetGroup) GetPresetArray() []*Preset {
	if x != nil {
		return x.PresetArray
	}
	return nil
}

func (x *PresetGroup) GetCanAddPreset() bool {
	if x != nil && x.CanAddPreset != nil {
		return *x.CanAddPreset
	}
	return false
}

func (x *PresetGroup) GetIcon() EnumPresetGroupIcon {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return EnumPresetGroupIcon_PRESET_GROUP_VIDEO_ICON_ID
}

func (x *PresetGroup) GetModeArray() []EnumFlatMode {
	if x != nil {
		return x.ModeArray
	}
	return nil
}

func (x *PresetGroup) GetCustomName() string {
	if x != nil && x.CustomName != nil {
		return *x.CustomName
	}
	return ""
}

func (x *PresetGroup) GetActivePresetId() int32 {
	if x != nil && x.ActivePresetId != nil {
		return *x.ActivePresetId
	}
	return 0
}

// *
// Setting representation that comprises a  @ref Preset
type PresetSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int32                 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`                                // Setting ID
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`                          // Setting value
	IsCaption     *bool                  `protobuf:"varint,3,opt,name=is_caption,json=isCaption" json:"is_caption,omitempty"` // Does this setting appear on the Preset "pill" in the camera UI?
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetSetting) Reset() {
	*x = PresetSetting{}
	mi := &file_preset_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetSetting) ProtoMessage() {}

func (x *PresetSetting) ProtoReflect() protoreflect.Message {
	mi := &file_preset_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetSetting.ProtoReflect.Descriptor instead.
func (*PresetSetting) Descriptor() ([]byte, []int) {
	return file_preset_status_proto_rawDescGZIP(), []int{5}
}

func (x *PresetSetting) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PresetSetting) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *PresetSetting) GetIsCaption() bool {
	if x != nil && x.IsCaption != nil {
		return *x.IsCaption
	}
	return false
}

var File_preset_status_proto protoreflect.FileDescriptor

const file_preset_status_proto_rawDesc = "" +
	"\n" +
	"\x13preset_status.proto\x12\n" +
	"open_gopro\x1a\x16response_generic.proto\"[\n" +
	"\x12NotifyPresetStatus\x12E\n" +
	"\x12preset_group_array\x18\x01 \x03(\v2\x17.open_gopro.PresetGroupR\x10presetGroupArray\"\xb0\x03\n" +
	"\x06Preset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x18.open_gopro.EnumFlatModeR\x04mode\x126\n" +
	"\btitle_id\x18\x03 \x01(\x0e2\x1b.open_gopro.EnumPresetTitleR\atitleId\x12!\n" +
	"\ftitle_number\x18\x04 \x01(\x05R\vtitleNumber\x12!\n" +
	"\fuser_defined\x18\x05 \x01(\bR\vuserDefined\x12.\n" +
	"\x04icon\x18\x06 \x01(\x0e2\x1a.open_gopro.EnumPresetIconR\x04icon\x12>\n" +
	"\rsetting_array\x18\a \x03(\v2\x19.open_gopro.PresetSettingR\fsettingArray\x12\x1f\n" +
	"\vis_modified\x18\b \x01(\bR\n" +
	"isModified\x12\x19\n" +
	"\bis_fixed\x18\t \x01(\bR\aisFixed\x12\x1f\n" +
	"\vcustom_name\x18\n" +
	" \x01(\tR\n" +
	"customName\x12\x1d\n" +
	"\n" +
	"is_visible\x18\v \x01(\bR\tisVisible\"\xa9\x01\n" +
	"\x19RequestCustomPresetUpdate\x126\n" +
	"\btitle_id\x18\x01 \x01(\x0e2\x1b.open_gopro.EnumPresetTitleR\atitleId\x12\x1f\n" +
	"\vcustom_name\x18\x02 \x01(\tR\n" +
	"customName\x123\n" +
	"\aicon_id\x18\x03 \x01(\x0e2\x1a.open_gopro.EnumPresetIconR\x06iconId\"F\n" +
	"\x1aRequestPresetSetVisibility\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\avisible\x18\x02 \x01(\bR\avisible\"\xd0\x02\n" +
	"\vPresetGroup\x12+\n" +
	"\x02id\x18\x01 \x01(\x0e2\x1b.open_gopro.EnumPresetGroupR\x02id\x125\n" +
	"\fpreset_array\x18\x02 \x03(\v2\x12.open_gopro.PresetR\vpresetArray\x12$\n" +
	"\x0ecan_add_preset\x18\x03 \x01(\bR\fcanAddPreset\x123\n" +
	"\x04icon\x18\x04 \x01(\x0e2\x1f.open_gopro.EnumPresetGroupIconR\x04icon\x127\n" +
	"\n" +
	"mode_array\x18\x05 \x03(\x0e2\x18.open_gopro.EnumFlatModeR\tmodeArray\x12\x1f\n" +
	"\vcustom_name\x18\x06 \x01(\tR\n" +
	"customName\x12(\n" +
	"\x10active_preset_id\x18\a \x01(\x05R\x0eactivePresetId\"T\n" +
	"\rPresetSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x1d\n" +
	"\n" +
	"is_caption\x18\x03 \x01(\bR\tisCaption*\x9b\x05\n" +
	"\fEnumFlatMode\x12\x1e\n" +
	"\x11FLAT_MODE_UNKNOWN\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x16\n" +
	"\x12FLAT_MODE_PLAYBACK\x10\x04\x12\x13\n" +
	"\x0fFLAT_MODE_SETUP\x10\x05\x12\x13\n" +
	"\x0fFLAT_MODE_VIDEO\x10\f\x12\x1e\n" +
	"\x1aFLAT_MODE_TIME_LAPSE_VIDEO\x10\r\x12\x15\n" +
	"\x11FLAT_MODE_LOOPING\x10\x0f\x12\x1a\n" +
	"\x16FLAT_MODE_PHOTO_SINGLE\x10\x10\x12\x13\n" +
	"\x0fFLAT_MODE_PHOTO\x10\x11\x12\x19\n" +
	"\x15FLAT_MODE_PHOTO_NIGHT\x10\x12\x12\x19\n" +
	"\x15FLAT_MODE_PHOTO_BURST\x10\x13\x12\x1e\n" +
	"\x1aFLAT_MODE_TIME_LAPSE_PHOTO\x10\x14\x12\x1f\n" +
	"\x1bFLAT_MODE_NIGHT_LAPSE_PHOTO\x10\x15\x12\x1e\n" +
	"\x1aFLAT_MODE_BROADCAST_RECORD\x10\x16\x12!\n" +
	"\x1dFLAT_MODE_BROADCAST_BROADCAST\x10\x17\x12\x1d\n" +
	"\x19FLAT_MODE_TIME_WARP_VIDEO\x10\x18\x12\x18\n" +
	"\x14FLAT_MODE_LIVE_BURST\x10\x19\x12\x1f\n" +
	"\x1bFLAT_MODE_NIGHT_LAPSE_VIDEO\x10\x1a\x12\x13\n" +
	"\x0fFLAT_MODE_SLOMO\x10\x1b\x12\x12\n" +
	"\x0eFLAT_MODE_IDLE\x10\x1c\x12\x1e\n" +
	"\x1aFLAT_MODE_VIDEO_STAR_TRAIL\x10\x1d\x12\"\n" +
	"\x1eFLAT_MODE_VIDEO_LIGHT_PAINTING\x10\x1e\x12\x1f\n" +
	"\x1bFLAT_MODE_VIDEO_LIGHT_TRAIL\x10\x1f\x12\x1f\n" +
	"\x1bFLAT_MODE_VIDEO_BURST_SLOMO\x10 *\x87\x01\n" +
	"\x0fEnumPresetGroup\x12\x1a\n" +
	"\x15PRESET_GROUP_ID_VIDEO\x10\xe8\a\x12\x1a\n" +
	"\x15PRESET_GROUP_ID_PHOTO\x10\xe9\a\x12\x1e\n" +
	"\x19PRESET_GROUP_ID_TIMELAPSE\x10\xea\a\x12\x1c\n" +
	"\x17PRESET_GROUP_ID_GENERAL\x10\xd0\x0f*\xb5\x03\n" +
	"\x13EnumPresetGroupIcon\x12\x1e\n" +
	"\x1aPRESET_GROUP_VIDEO_ICON_ID\x10\x00\x12\x1e\n" +
	"\x1aPRESET_GROUP_PHOTO_ICON_ID\x10\x01\x12\"\n" +
	"\x1ePRESET_GROUP_TIMELAPSE_ICON_ID\x10\x02\x12'\n" +
	"#PRESET_GROUP_LONG_BAT_VIDEO_ICON_ID\x10\x03\x12(\n" +
	"$PRESET_GROUP_ENDURANCE_VIDEO_ICON_ID\x10\x04\x12\"\n" +
	"\x1ePRESET_GROUP_MAX_VIDEO_ICON_ID\x10\x05\x12\"\n" +
	"\x1ePRESET_GROUP_MAX_PHOTO_ICON_ID\x10\x06\x12&\n" +
	"\"PRESET_GROUP_MAX_TIMELAPSE_ICON_ID\x10\a\x12%\n" +
	"!PRESET_GROUP_ND_MOD_VIDEO_ICON_ID\x10\b\x12%\n" +
	"!PRESET_GROUP_ND_MOD_PHOTO_ICON_ID\x10\t\x12)\n" +
	"%PRESET_GROUP_ND_MOD_TIMELAPSE_ICON_ID\x10\n" +
	"*\xff\x12\n" +
	"\x0eEnumPresetIcon\x12\x15\n" +
	"\x11PRESET_ICON_VIDEO\x10\x00\x12\x18\n" +
	"\x14PRESET_ICON_ACTIVITY\x10\x01\x12\x19\n" +
	"\x15PRESET_ICON_CINEMATIC\x10\x02\x12\x15\n" +
	"\x11PRESET_ICON_PHOTO\x10\x03\x12\x1a\n" +
	"\x16PRESET_ICON_LIVE_BURST\x10\x04\x12\x15\n" +
	"\x11PRESET_ICON_BURST\x10\x05\x12\x1b\n" +
	"\x17PRESET_ICON_PHOTO_NIGHT\x10\x06\x12\x18\n" +
	"\x14PRESET_ICON_TIMEWARP\x10\a\x12\x19\n" +
	"\x15PRESET_ICON_TIMELAPSE\x10\b\x12\x1a\n" +
	"\x16PRESET_ICON_NIGHTLAPSE\x10\t\x12\x15\n" +
	"\x11PRESET_ICON_SNAIL\x10\n" +
	"\x12\x17\n" +
	"\x13PRESET_ICON_VIDEO_2\x10\v\x12\x17\n" +
	"\x13PRESET_ICON_PHOTO_2\x10\r\x12\x18\n" +
	"\x14PRESET_ICON_PANORAMA\x10\x0e\x12\x17\n" +
	"\x13PRESET_ICON_BURST_2\x10\x0f\x12\x1a\n" +
	"\x16PRESET_ICON_TIMEWARP_2\x10\x10\x12\x1b\n" +
	"\x17PRESET_ICON_TIMELAPSE_2\x10\x11\x12\x16\n" +
	"\x12PRESET_ICON_CUSTOM\x10\x12\x12\x13\n" +
	"\x0fPRESET_ICON_AIR\x10\x13\x12\x14\n" +
	"\x10PRESET_ICON_BIKE\x10\x14\x12\x14\n" +
	"\x10PRESET_ICON_EPIC\x10\x15\x12\x16\n" +
	"\x12PRESET_ICON_INDOOR\x10\x16\x12\x15\n" +
	"\x11PRESET_ICON_MOTOR\x10\x17\x12\x17\n" +
	"\x13PRESET_ICON_MOUNTED\x10\x18\x12\x17\n" +
	"\x13PRESET_ICON_OUTDOOR\x10\x19\x12\x13\n" +
	"\x0fPRESET_ICON_POV\x10\x1a\x12\x16\n" +
	"\x12PRESET_ICON_SELFIE\x10\x1b\x12\x15\n" +
	"\x11PRESET_ICON_SKATE\x10\x1c\x12\x14\n" +
	"\x10PRESET_ICON_SNOW\x10\x1d\x12\x15\n" +
	"\x11PRESET_ICON_TRAIL\x10\x1e\x12\x16\n" +
	"\x12PRESET_ICON_TRAVEL\x10\x1f\x12\x15\n" +
	"\x11PRESET_ICON_WATER\x10 \x12\x17\n" +
	"\x13PRESET_ICON_LOOPING\x10!\x12\x15\n" +
	"\x11PRESET_ICON_STARS\x10\"\x12\x16\n" +
	"\x12PRESET_ICON_ACTION\x10#\x12\x1a\n" +
	"\x16PRESET_ICON_FOLLOW_CAM\x10$\x12\x14\n" +
	"\x10PRESET_ICON_SURF\x10%\x12\x14\n" +
	"\x10PRESET_ICON_CITY\x10&\x12\x15\n" +
	"\x11PRESET_ICON_SHAKY\x10'\x12\x16\n" +
	"\x12PRESET_ICON_CHESTY\x10(\x12\x16\n" +
	"\x12PRESET_ICON_HELMET\x10)\x12\x14\n" +
	"\x10PRESET_ICON_BITE\x10*\x12 \n" +
	"\x1cPRESET_ICON_CUSTOM_CINEMATIC\x10+\x12\x14\n" +
	"\x10PRESET_ICON_VLOG\x10,\x12\x13\n" +
	"\x0fPRESET_ICON_FPV\x10-\x12\x13\n" +
	"\x0fPRESET_ICON_HDR\x10.\x12\x19\n" +
	"\x15PRESET_ICON_LANDSCAPE\x10/\x12\x13\n" +
	"\x0fPRESET_ICON_LOG\x100\x12\x1c\n" +
	"\x18PRESET_ICON_CUSTOM_SLOMO\x101\x12\x16\n" +
	"\x12PRESET_ICON_TRIPOD\x102\x12\x19\n" +
	"\x15PRESET_ICON_MAX_VIDEO\x107\x12\x19\n" +
	"\x15PRESET_ICON_MAX_PHOTO\x108\x12\x1c\n" +
	"\x18PRESET_ICON_MAX_TIMEWARP\x109\x12\x15\n" +
	"\x11PRESET_ICON_BASIC\x10:\x12\x1c\n" +
	"\x18PRESET_ICON_ULTRA_SLO_MO\x10;\x12\"\n" +
	"\x1ePRESET_ICON_STANDARD_ENDURANCE\x10<\x12\"\n" +
	"\x1ePRESET_ICON_ACTIVITY_ENDURANCE\x10=\x12#\n" +
	"\x1fPRESET_ICON_CINEMATIC_ENDURANCE\x10>\x12\x1f\n" +
	"\x1bPRESET_ICON_SLOMO_ENDURANCE\x10?\x12\x1c\n" +
	"\x18PRESET_ICON_STATIONARY_1\x10@\x12\x1c\n" +
	"\x18PRESET_ICON_STATIONARY_2\x10A\x12\x1c\n" +
	"\x18PRESET_ICON_STATIONARY_3\x10B\x12\x1c\n" +
	"\x18PRESET_ICON_STATIONARY_4\x10C\x12\"\n" +
	"\x1ePRESET_ICON_SIMPLE_SUPER_PHOTO\x10F\x12\"\n" +
	"\x1ePRESET_ICON_SIMPLE_NIGHT_PHOTO\x10G\x12%\n" +
	"!PRESET_ICON_HIGHEST_QUALITY_VIDEO\x10I\x12&\n" +
	"\"PRESET_ICON_STANDARD_QUALITY_VIDEO\x10J\x12#\n" +
	"\x1fPRESET_ICON_BASIC_QUALITY_VIDEO\x10K\x12\x1a\n" +
	"\x16PRESET_ICON_STAR_TRAIL\x10L\x12\x1e\n" +
	"\x1aPRESET_ICON_LIGHT_PAINTING\x10M\x12\x1b\n" +
	"\x17PRESET_ICON_LIGHT_TRAIL\x10N\x12\x1a\n" +
	"\x16PRESET_ICON_FULL_FRAME\x10O\x12\x1e\n" +
	"\x1aPRESET_ICON_EASY_MAX_VIDEO\x10P\x12\x1e\n" +
	"\x1aPRESET_ICON_EASY_MAX_PHOTO\x10Q\x12!\n" +
	"\x1dPRESET_ICON_EASY_MAX_TIMEWARP\x10R\x12#\n" +
	"\x1fPRESET_ICON_EASY_MAX_STAR_TRAIL\x10S\x12'\n" +
	"#PRESET_ICON_EASY_MAX_LIGHT_PAINTING\x10T\x12$\n" +
	" PRESET_ICON_EASY_MAX_LIGHT_TRAIL\x10U\x12\x1e\n" +
	"\x1aPRESET_ICON_MAX_STAR_TRAIL\x10Y\x12\"\n" +
	"\x1ePRESET_ICON_MAX_LIGHT_PAINTING\x10Z\x12\x1f\n" +
	"\x1bPRESET_ICON_MAX_LIGHT_TRAIL\x10[\x12%\n" +
	"!PRESET_ICON_EASY_STANDARD_PROFILE\x10d\x12 \n" +
	"\x1cPRESET_ICON_EASY_HDR_PROFILE\x10e\x12\x1b\n" +
	"\x17PRESET_ICON_BURST_SLOMO\x10f\x12 \n" +
	"\x1bPRESET_ICON_TIMELAPSE_PHOTO\x10\xe8\a\x12!\n" +
	"\x1cPRESET_ICON_NIGHTLAPSE_PHOTO\x10\xe9\a*\x9f\x13\n" +
	"\x0fEnumPresetTitle\x12\x19\n" +
	"\x15PRESET_TITLE_ACTIVITY\x10\x00\x12\x19\n" +
	"\x15PRESET_TITLE_STANDARD\x10\x01\x12\x1a\n" +
	"\x16PRESET_TITLE_CINEMATIC\x10\x02\x12\x16\n" +
	"\x12PRESET_TITLE_PHOTO\x10\x03\x12\x1b\n" +
	"\x17PRESET_TITLE_LIVE_BURST\x10\x04\x12\x16\n" +
	"\x12PRESET_TITLE_BURST\x10\x05\x12\x16\n" +
	"\x12PRESET_TITLE_NIGHT\x10\x06\x12\x1a\n" +
	"\x16PRESET_TITLE_TIME_WARP\x10\a\x12\x1b\n" +
	"\x17PRESET_TITLE_TIME_LAPSE\x10\b\x12\x1c\n" +
	"\x18PRESET_TITLE_NIGHT_LAPSE\x10\t\x12\x16\n" +
	"\x12PRESET_TITLE_VIDEO\x10\n" +
	"\x12\x16\n" +
	"\x12PRESET_TITLE_SLOMO\x10\v\x12\x18\n" +
	"\x14PRESET_TITLE_PHOTO_2\x10\r\x12\x19\n" +
	"\x15PRESET_TITLE_PANORAMA\x10\x0e\x12\x1c\n" +
	"\x18PRESET_TITLE_TIME_WARP_2\x10\x10\x12\x17\n" +
	"\x13PRESET_TITLE_CUSTOM\x10\x12\x12\x14\n" +
	"\x10PRESET_TITLE_AIR\x10\x13\x12\x15\n" +
	"\x11PRESET_TITLE_BIKE\x10\x14\x12\x15\n" +
	"\x11PRESET_TITLE_EPIC\x10\x15\x12\x17\n" +
	"\x13PRESET_TITLE_INDOOR\x10\x16\x12\x16\n" +
	"\x12PRESET_TITLE_MOTOR\x10\x17\x12\x18\n" +
	"\x14PRESET_TITLE_MOUNTED\x10\x18\x12\x18\n" +
	"\x14PRESET_TITLE_OUTDOOR\x10\x19\x12\x14\n" +
	"\x10PRESET_TITLE_POV\x10\x1a\x12\x17\n" +
	"\x13PRESET_TITLE_SELFIE\x10\x1b\x12\x16\n" +
	"\x12PRESET_TITLE_SKATE\x10\x1c\x12\x15\n" +
	"\x11PRESET_TITLE_SNOW\x10\x1d\x12\x16\n" +
	"\x12PRESET_TITLE_TRAIL\x10\x1e\x12\x17\n" +
	"\x13PRESET_TITLE_TRAVEL\x10\x1f\x12\x16\n" +
	"\x12PRESET_TITLE_WATER\x10 \x12\x18\n" +
	"\x14PRESET_TITLE_LOOPING\x10!\x12\x16\n" +
	"\x12PRESET_TITLE_STARS\x10\"\x12\x17\n" +
	"\x13PRESET_TITLE_ACTION\x10#\x12\x1b\n" +
	"\x17PRESET_TITLE_FOLLOW_CAM\x10$\x12\x15\n" +
	"\x11PRESET_TITLE_SURF\x10%\x12\x15\n" +
	"\x11PRESET_TITLE_CITY\x10&\x12\x16\n" +
	"\x12PRESET_TITLE_SHAKY\x10'\x12\x17\n" +
	"\x13PRESET_TITLE_CHESTY\x10(\x12\x17\n" +
	"\x13PRESET_TITLE_HELMET\x10)\x12\x15\n" +
	"\x11PRESET_TITLE_BITE\x10*\x12!\n" +
	"\x1dPRESET_TITLE_CUSTOM_CINEMATIC\x10+\x12\x15\n" +
	"\x11PRESET_TITLE_VLOG\x10,\x12\x14\n" +
	"\x10PRESET_TITLE_FPV\x10-\x12\x14\n" +
	"\x10PRESET_TITLE_HDR\x10.\x12\x1a\n" +
	"\x16PRESET_TITLE_LANDSCAPE\x10/\x12\x14\n" +
	"\x10PRESET_TITLE_LOG\x100\x12\x1d\n" +
	"\x19PRESET_TITLE_CUSTOM_SLOMO\x101\x12\x17\n" +
	"\x13PRESET_TITLE_TRIPOD\x102\x12\x16\n" +
	"\x12PRESET_TITLE_BASIC\x10:\x12\x1d\n" +
	"\x19PRESET_TITLE_ULTRA_SLO_MO\x10;\x12#\n" +
	"\x1fPRESET_TITLE_STANDARD_ENDURANCE\x10<\x12#\n" +
	"\x1fPRESET_TITLE_ACTIVITY_ENDURANCE\x10=\x12$\n" +
	" PRESET_TITLE_CINEMATIC_ENDURANCE\x10>\x12 \n" +
	"\x1cPRESET_TITLE_SLOMO_ENDURANCE\x10?\x12\x1d\n" +
	"\x19PRESET_TITLE_STATIONARY_1\x10@\x12\x1d\n" +
	"\x19PRESET_TITLE_STATIONARY_2\x10A\x12\x1d\n" +
	"\x19PRESET_TITLE_STATIONARY_3\x10B\x12\x1d\n" +
	"\x19PRESET_TITLE_STATIONARY_4\x10C\x12\x1d\n" +
	"\x19PRESET_TITLE_SIMPLE_VIDEO\x10D\x12!\n" +
	"\x1dPRESET_TITLE_SIMPLE_TIME_WARP\x10E\x12#\n" +
	"\x1fPRESET_TITLE_SIMPLE_SUPER_PHOTO\x10F\x12#\n" +
	"\x1fPRESET_TITLE_SIMPLE_NIGHT_PHOTO\x10G\x12'\n" +
	"#PRESET_TITLE_SIMPLE_VIDEO_ENDURANCE\x10H\x12 \n" +
	"\x1cPRESET_TITLE_HIGHEST_QUALITY\x10I\x12!\n" +
	"\x1dPRESET_TITLE_EXTENDED_BATTERY\x10J\x12 \n" +
	"\x1cPRESET_TITLE_LONGEST_BATTERY\x10K\x12\x1b\n" +
	"\x17PRESET_TITLE_STAR_TRAIL\x10L\x12\x1f\n" +
	"\x1bPRESET_TITLE_LIGHT_PAINTING\x10M\x12\x1c\n" +
	"\x18PRESET_TITLE_LIGHT_TRAIL\x10N\x12\x1b\n" +
	"\x17PRESET_TITLE_FULL_FRAME\x10O\x12'\n" +
	"#PRESET_TITLE_STANDARD_QUALITY_VIDEO\x10R\x12$\n" +
	" PRESET_TITLE_BASIC_QUALITY_VIDEO\x10S\x12&\n" +
	"\"PRESET_TITLE_HIGHEST_QUALITY_VIDEO\x10]\x12)\n" +
	"%PRESET_TITLE_USER_DEFINED_CUSTOM_NAME\x10^\x12&\n" +
	"\"PRESET_TITLE_EASY_STANDARD_PROFILE\x10c\x12!\n" +
	"\x1dPRESET_TITLE_EASY_HDR_PROFILE\x10d\x12\x1c\n" +
	"\x18PRESET_TITLE_BURST_SLOMO\x10j\x12\x1a\n" +
	"\x16PRESET_TITLE_4_3_VIDEO\x10}\x12\x1b\n" +
	"\x17PRESET_TITLE_16_9_VIDEO\x10~\x12\x1b\n" +
	"\x17PRESET_TITLE_16_9_SLOMO\x10\x7f\x12\"\n" +
	"\x1dPRESET_TITLE_TIME_LAPSE_VIDEO\x10\x83\x01\x12\"\n" +
	"\x1dPRESET_TITLE_TIME_LAPSE_PHOTO\x10\x84\x01\x12#\n" +
	"\x1ePRESET_TITLE_NIGHT_LAPSE_VIDEO\x10\x85\x01\x12#\n" +
	"\x1ePRESET_TITLE_NIGHT_LAPSE_PHOTO\x10\x86\x01"

var (
	file_preset_status_proto_rawDescOnce sync.Once
	file_preset_status_proto_rawDescData []byte
)

func file_preset_status_proto_rawDescGZIP() []byte {
	file_preset_status_proto_rawDescOnce.Do(func() {
		file_preset_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preset_status_proto_rawDesc), len(file_preset_status_proto_rawDesc)))
	})
	return file_preset_status_proto_rawDescData
}

var file_preset_status_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_preset_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_preset_status_proto_goTypes = []any{
	(EnumFlatMode)(0),                  // 0: open_gopro.EnumFlatMode
	(EnumPresetGroup)(0),               // 1: open_gopro.EnumPresetGroup
	(EnumPresetGroupIcon)(0),           // 2: open_gopro.EnumPresetGroupIcon
	(EnumPresetIcon)(0),                // 3: open_gopro.EnumPresetIcon
	(EnumPresetTitle)(0),               // 4: open_gopro.EnumPresetTitle
	(*NotifyPresetStatus)(nil),         // 5: open_gopro.NotifyPresetStatus
	(*Preset)(nil),                     // 6: open_gopro.Preset
	(*RequestCustomPresetUpdate)(nil),  // 7: open_gopro.RequestCustomPresetUpdate
	(*RequestPresetSetVisibility)(nil), // 8: open_gopro.RequestPresetSetVisibility
	(*PresetGroup)(nil),                // 9: open_gopro.PresetGroup
	(*PresetSetting)(nil),              // 10: open_gopro.PresetSetting
}
var file_preset_status_proto_depIdxs = []int32{
	9,  // 0: open_gopro.NotifyPresetStatus.preset_group_array:type_name -> open_gopro.PresetGroup
	0,  // 1: open_gopro.Preset.mode:type_name -> open_gopro.EnumFlatMode
	4,  // 2: open_gopro.Preset.title_id:type_name -> open_gopro.EnumPresetTitle
	3,  // 3: open_gopro.Preset.icon:type_name -> open_gopro.EnumPresetIcon
	10, // 4: open_gopro.Preset.setting_array:type_name -> open_gopro.PresetSetting
	4,  // 5: open_gopro.RequestCustomPresetUpdate.title_id:type_name -> open_gopro.EnumPresetTitle
	3,  // 6: open_gopro.RequestCustomPresetUpdate.icon_id:type_name -> open_gopro.EnumPresetIcon
	1,  // 7: open_gopro.PresetGroup.id:type_name -> open_gopro.EnumPresetGroup
	6,  // 8: open_gopro.PresetGroup.preset_array:type_name -> open_gopro.Preset
	2,  // 9: open_gopro.PresetGroup.icon:type_name -> open_gopro.EnumPresetGroupIcon
	0,  // 10: open_gopro.PresetGroup.mode_array:type_name -> open_gopro.EnumFlatMode
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_preset_status_proto_init() }
func file_preset_status_proto_init() {
	if File_preset_status_proto != nil {
		return
	}
	file_response_generic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preset_status_proto_rawDesc), len(file_preset_status_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_preset_status_proto_goTypes,
		DependencyIndexes: file_preset_status_proto_depIdxs,
		EnumInfos:         file_preset_status_proto_enumTypes,
		MessageInfos:      file_preset_status_proto_msgTypes,
	}.Build()
	File_preset_status_proto = out.File
	file_preset_status_proto_goTypes = nil
	file_preset_status_proto_depIdxs = nil
}
