// request_get_preset_status.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Mon Nov  4 18:00:55 UTC 2024

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf messages for obtaining preset status

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: request_get_preset_status.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumRegisterPresetStatus int32

const (
	EnumRegisterPresetStatus_REGISTER_PRESET_STATUS_PRESET             EnumRegisterPresetStatus = 1 // Send notification when properties of a preset change
	EnumRegisterPresetStatus_REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY EnumRegisterPresetStatus = 2 // Send notification when properties of a preset group change
)

// Enum value maps for EnumRegisterPresetStatus.
var (
	EnumRegisterPresetStatus_name = map[int32]string{
		1: "REGISTER_PRESET_STATUS_PRESET",
		2: "REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY",
	}
	EnumRegisterPresetStatus_value = map[string]int32{
		"REGISTER_PRESET_STATUS_PRESET":             1,
		"REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY": 2,
	}
)

func (x EnumRegisterPresetStatus) Enum() *EnumRegisterPresetStatus {
	p := new(EnumRegisterPresetStatus)
	*p = x
	return p
}

func (x EnumRegisterPresetStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumRegisterPresetStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_request_get_preset_status_proto_enumTypes[0].Descriptor()
}

func (EnumRegisterPresetStatus) Type() protoreflect.EnumType {
	return &file_request_get_preset_status_proto_enumTypes[0]
}

func (x EnumRegisterPresetStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumRegisterPresetStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumRegisterPresetStatus(num)
	return nil
}

// Deprecated: Use EnumRegisterPresetStatus.Descriptor instead.
func (EnumRegisterPresetStatus) EnumDescriptor() ([]byte, []int) {
	return file_request_get_preset_status_proto_rawDescGZIP(), []int{0}
}

// *
// Get the set of currently available presets and optionally register to be notified when it changes.
//
// Response: @ref NotifyPresetStatus sent immediately
//
// Notification: @ref NotifyPresetStatus sent periodically as preset status changes, if registered.
//
// The preset status changes when:
//
// - A client changes one of a preset's captioned settings via the API
// - The user exits from a preset's settings UI on the camera (e.g. long-press the preset pill and then press the back arrow)
// - The user creates/deletes/reorders a preset within a group
type RequestGetPresetStatus struct {
	state                  protoimpl.MessageState     `protogen:"open.v1"`
	RegisterPresetStatus   []EnumRegisterPresetStatus `protobuf:"varint,1,rep,name=register_preset_status,json=registerPresetStatus,enum=open_gopro.EnumRegisterPresetStatus" json:"register_preset_status,omitempty"`       // Array of Preset statuses to be notified about
	UnregisterPresetStatus []EnumRegisterPresetStatus `protobuf:"varint,2,rep,name=unregister_preset_status,json=unregisterPresetStatus,enum=open_gopro.EnumRegisterPresetStatus" json:"unregister_preset_status,omitempty"` // Array of Preset statuses to stop being notified about
	// *
	// Configures the set of Setting IDs that are returned by @ref NotifyPresetStatus.
	//
	// # Defaults to False if not set
	//
	// When False, Setting IDs are tied to their camera UI string representation and may vary between cameras.
	//
	// When True, Setting IDs are tied to their functional representation and are consistent across cameras.
	UseConstantSettingIds *bool `protobuf:"varint,3,opt,name=use_constant_setting_ids,json=useConstantSettingIds" json:"use_constant_setting_ids,omitempty"`
	// *
	// Whether to include hidden presets
	//
	// When True, all currently available presets will be included in the response, even those hidden by the
	// camera UI
	//
	// When False, only currently available presets that are displayed in the camera UI are included in the response.
	//
	// Note that a Preset's visibility can be configured by @ref RequestPresetSetVisibility.
	IncludeHidden *bool `protobuf:"varint,4,opt,name=include_hidden,json=includeHidden" json:"include_hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestGetPresetStatus) Reset() {
	*x = RequestGetPresetStatus{}
	mi := &file_request_get_preset_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestGetPresetStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetPresetStatus) ProtoMessage() {}

func (x *RequestGetPresetStatus) ProtoReflect() protoreflect.Message {
	mi := &file_request_get_preset_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetPresetStatus.ProtoReflect.Descriptor instead.
func (*RequestGetPresetStatus) Descriptor() ([]byte, []int) {
	return file_request_get_preset_status_proto_rawDescGZIP(), []int{0}
}

func (x *RequestGetPresetStatus) GetRegisterPresetStatus() []EnumRegisterPresetStatus {
	if x != nil {
		return x.RegisterPresetStatus
	}
	return nil
}

func (x *RequestGetPresetStatus) GetUnregisterPresetStatus() []EnumRegisterPresetStatus {
	if x != nil {
		return x.UnregisterPresetStatus
	}
	return nil
}

func (x *RequestGetPresetStatus) GetUseConstantSettingIds() bool {
	if x != nil && x.UseConstantSettingIds != nil {
		return *x.UseConstantSettingIds
	}
	return false
}

func (x *RequestGetPresetStatus) GetIncludeHidden() bool {
	if x != nil && x.IncludeHidden != nil {
		return *x.IncludeHidden
	}
	return false
}

var File_request_get_preset_status_proto protoreflect.FileDescriptor

const file_request_get_preset_status_proto_rawDesc = "" +
	"\n" +
	"\x1frequest_get_preset_status.proto\x12\n" +
	"open_gopro\"\xb4\x02\n" +
	"\x16RequestGetPresetStatus\x12Z\n" +
	"\x16register_preset_status\x18\x01 \x03(\x0e2$.open_gopro.EnumRegisterPresetStatusR\x14registerPresetStatus\x12^\n" +
	"\x18unregister_preset_status\x18\x02 \x03(\x0e2$.open_gopro.EnumRegisterPresetStatusR\x16unregisterPresetStatus\x127\n" +
	"\x18use_constant_setting_ids\x18\x03 \x01(\bR\x15useConstantSettingIds\x12%\n" +
	"\x0einclude_hidden\x18\x04 \x01(\bR\rincludeHidden*l\n" +
	"\x18EnumRegisterPresetStatus\x12!\n" +
	"\x1dREGISTER_PRESET_STATUS_PRESET\x10\x01\x12-\n" +
	")REGISTER_PRESET_STATUS_PRESET_GROUP_ARRAY\x10\x02"

var (
	file_request_get_preset_status_proto_rawDescOnce sync.Once
	file_request_get_preset_status_proto_rawDescData []byte
)

func file_request_get_preset_status_proto_rawDescGZIP() []byte {
	file_request_get_preset_status_proto_rawDescOnce.Do(func() {
		file_request_get_preset_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_get_preset_status_proto_rawDesc), len(file_request_get_preset_status_proto_rawDesc)))
	})
	return file_request_get_preset_status_proto_rawDescData
}

var file_request_get_preset_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_request_get_preset_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_get_preset_status_proto_goTypes = []any{
	(EnumRegisterPresetStatus)(0),  // 0: open_gopro.EnumRegisterPresetStatus
	(*RequestGetPresetStatus)(nil), // 1: open_gopro.RequestGetPresetStatus
}
var file_request_get_preset_status_proto_depIdxs = []int32{
	0, // 0: open_gopro.RequestGetPresetStatus.register_preset_status:type_name -> open_gopro.EnumRegisterPresetStatus
	0, // 1: open_gopro.RequestGetPresetStatus.unregister_preset_status:type_name -> open_gopro.EnumRegisterPresetStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_get_preset_status_proto_init() }
func file_request_get_preset_status_proto_init() {
	if File_request_get_preset_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_get_preset_status_proto_rawDesc), len(file_request_get_preset_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_get_preset_status_proto_goTypes,
		DependencyIndexes: file_request_get_preset_status_proto_depIdxs,
		EnumInfos:         file_request_get_preset_status_proto_enumTypes,
		MessageInfos:      file_request_get_preset_status_proto_msgTypes,
	}.Build()
	File_request_get_preset_status_proto = out.File
	file_request_get_preset_status_proto_goTypes = nil
	file_request_get_preset_status_proto_depIdxs = nil
}
