// response_generic.proto/Open GoPro, Version 2.0 (C) Copyright 2021 GoPro, Inc. (http://gopro.com/OpenGoPro).

// This copyright was auto-generated on Mon Nov  4 18:00:55 UTC 2024

//**********************************************************************************************************************
//
// This file is automatically generated!!! Do not modify manually.
//
//********************************************************************************************************************

//*
// Defines the structure of protobuf message containing generic response to a command

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: response_generic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnumResultGeneric int32

const (
	EnumResultGeneric_RESULT_UNKNOWN                EnumResultGeneric = 0
	EnumResultGeneric_RESULT_SUCCESS                EnumResultGeneric = 1
	EnumResultGeneric_RESULT_ILL_FORMED             EnumResultGeneric = 2
	EnumResultGeneric_RESULT_NOT_SUPPORTED          EnumResultGeneric = 3
	EnumResultGeneric_RESULT_ARGUMENT_OUT_OF_BOUNDS EnumResultGeneric = 4
	EnumResultGeneric_RESULT_ARGUMENT_INVALID       EnumResultGeneric = 5
	EnumResultGeneric_RESULT_RESOURCE_NOT_AVAILABLE EnumResultGeneric = 6
)

// Enum value maps for EnumResultGeneric.
var (
	EnumResultGeneric_name = map[int32]string{
		0: "RESULT_UNKNOWN",
		1: "RESULT_SUCCESS",
		2: "RESULT_ILL_FORMED",
		3: "RESULT_NOT_SUPPORTED",
		4: "RESULT_ARGUMENT_OUT_OF_BOUNDS",
		5: "RESULT_ARGUMENT_INVALID",
		6: "RESULT_RESOURCE_NOT_AVAILABLE",
	}
	EnumResultGeneric_value = map[string]int32{
		"RESULT_UNKNOWN":                0,
		"RESULT_SUCCESS":                1,
		"RESULT_ILL_FORMED":             2,
		"RESULT_NOT_SUPPORTED":          3,
		"RESULT_ARGUMENT_OUT_OF_BOUNDS": 4,
		"RESULT_ARGUMENT_INVALID":       5,
		"RESULT_RESOURCE_NOT_AVAILABLE": 6,
	}
)

func (x EnumResultGeneric) Enum() *EnumResultGeneric {
	p := new(EnumResultGeneric)
	*p = x
	return p
}

func (x EnumResultGeneric) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumResultGeneric) Descriptor() protoreflect.EnumDescriptor {
	return file_response_generic_proto_enumTypes[0].Descriptor()
}

func (EnumResultGeneric) Type() protoreflect.EnumType {
	return &file_response_generic_proto_enumTypes[0]
}

func (x EnumResultGeneric) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnumResultGeneric) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnumResultGeneric(num)
	return nil
}

// Deprecated: Use EnumResultGeneric.Descriptor instead.
func (EnumResultGeneric) EnumDescriptor() ([]byte, []int) {
	return file_response_generic_proto_rawDescGZIP(), []int{0}
}

// Generic Response used across many response / notification messages
type ResponseGeneric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *EnumResultGeneric     `protobuf:"varint,1,req,name=result,enum=open_gopro.EnumResultGeneric" json:"result,omitempty"` // Generic pass/fail/error info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseGeneric) Reset() {
	*x = ResponseGeneric{}
	mi := &file_response_generic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGeneric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGeneric) ProtoMessage() {}

func (x *ResponseGeneric) ProtoReflect() protoreflect.Message {
	mi := &file_response_generic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGeneric.ProtoReflect.Descriptor instead.
func (*ResponseGeneric) Descriptor() ([]byte, []int) {
	return file_response_generic_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGeneric) GetResult() EnumResultGeneric {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return EnumResultGeneric_RESULT_UNKNOWN
}

// *
// A common model to represent a media file
type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folder        *string                `protobuf:"bytes,1,opt,name=folder" json:"folder,omitempty"` // Directory in which the media is contained
	File          *string                `protobuf:"bytes,2,opt,name=file" json:"file,omitempty"`     // Filename of media
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_response_generic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_response_generic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_response_generic_proto_rawDescGZIP(), []int{1}
}

func (x *Media) GetFolder() string {
	if x != nil && x.Folder != nil {
		return *x.Folder
	}
	return ""
}

func (x *Media) GetFile() string {
	if x != nil && x.File != nil {
		return *x.File
	}
	return ""
}

var File_response_generic_proto protoreflect.FileDescriptor

const file_response_generic_proto_rawDesc = "" +
	"\n" +
	"\x16response_generic.proto\x12\n" +
	"open_gopro\"H\n" +
	"\x0fResponseGeneric\x125\n" +
	"\x06result\x18\x01 \x02(\x0e2\x1d.open_gopro.EnumResultGenericR\x06result\"3\n" +
	"\x05Media\x12\x16\n" +
	"\x06folder\x18\x01 \x01(\tR\x06folder\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file*\xcf\x01\n" +
	"\x11EnumResultGeneric\x12\x12\n" +
	"\x0eRESULT_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eRESULT_SUCCESS\x10\x01\x12\x15\n" +
	"\x11RESULT_ILL_FORMED\x10\x02\x12\x18\n" +
	"\x14RESULT_NOT_SUPPORTED\x10\x03\x12!\n" +
	"\x1dRESULT_ARGUMENT_OUT_OF_BOUNDS\x10\x04\x12\x1b\n" +
	"\x17RESULT_ARGUMENT_INVALID\x10\x05\x12!\n" +
	"\x1dRESULT_RESOURCE_NOT_AVAILABLE\x10\x06"

var (
	file_response_generic_proto_rawDescOnce sync.Once
	file_response_generic_proto_rawDescData []byte
)

func file_response_generic_proto_rawDescGZIP() []byte {
	file_response_generic_proto_rawDescOnce.Do(func() {
		file_response_generic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_generic_proto_rawDesc), len(file_response_generic_proto_rawDesc)))
	})
	return file_response_generic_proto_rawDescData
}

var file_response_generic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_generic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_response_generic_proto_goTypes = []any{
	(EnumResultGeneric)(0),  // 0: open_gopro.EnumResultGeneric
	(*ResponseGeneric)(nil), // 1: open_gopro.ResponseGeneric
	(*Media)(nil),           // 2: open_gopro.Media
}
var file_response_generic_proto_depIdxs = []int32{
	0, // 0: open_gopro.ResponseGeneric.result:type_name -> open_gopro.EnumResultGeneric
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_response_generic_proto_init() }
func file_response_generic_proto_init() {
	if File_response_generic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_generic_proto_rawDesc), len(file_response_generic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_generic_proto_goTypes,
		DependencyIndexes: file_response_generic_proto_depIdxs,
		EnumInfos:         file_response_generic_proto_enumTypes,
		MessageInfos:      file_response_generic_proto_msgTypes,
	}.Build()
	File_response_generic_proto = out.File
	file_response_generic_proto_goTypes = nil
	file_response_generic_proto_depIdxs = nil
}
